SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema etafakna
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema etafakna
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `etafakna`;

CREATE SCHEMA IF NOT EXISTS `etafakna` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE `etafakna`;
-- -----------------------------------------------------
-- Table `etafakna`.`contract_types`
-- -----------------------------------------------------

 CREATE TABLE IF NOT EXISTS `etafakna`.`contract_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `signed_time` INT NULL DEFAULT NULL,
  `time_answering` INT NOT NULL,
  `title_EN` VARCHAR(200) NULL DEFAULT NULL,
  `title_FR` VARCHAR(200) NULL DEFAULT NULL,
  `title_AR` VARCHAR(200) NULL DEFAULT NULL,
  `description_EN` VARCHAR(1000) NULL DEFAULT NULL,
  `description_FR` VARCHAR(1000) NULL DEFAULT NULL,
  `description_AR` VARCHAR(1000) NULL DEFAULT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `template_EN` VARCHAR(1000) NULL DEFAULT NULL,
  `template_FR` VARCHAR(1000) NULL DEFAULT NULL,
  `template_AR` VARCHAR(1000) NULL DEFAULT NULL,
  `country` VARCHAR(10) NULL DEFAULT NULL,
  `types` VARCHAR(10) NULL DEFAULT NULL,
  `categories` VARCHAR(10) NULL DEFAULT NULL,
  `inside_categories` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 18 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

 ALTER TABLE `etafakna`.`contract_types` AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `etafakna`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_url` VARCHAR(255) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `created_at` VARCHAR(50) NULL DEFAULT NULL,
  `contract_image` VARCHAR(255) NULL DEFAULT NULL,
  `contract_types_id` INT NOT NULL,
  `archieve` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `contract_types_id`),
  INDEX `fk_contracts_contract_types1_idx` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_contract_types1` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_EN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_EN` VARCHAR(100) NOT NULL,
  `part2_EN` VARCHAR(50) NULL,
  `inputType` LONGTEXT NOT NULL,
  `options` VARCHAR(250),
  `date` VARCHAR(10) NOT NULL,
  `explanation` VARCHAR(1000),
  `text_Area` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
-- -----------------------------------------------------
-- Table `etafakna`.` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_FR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_FR` VARCHAR(100) NOT NULL,
  `part2_FR` VARCHAR(50) NULL,
  `inputType` LONGTEXT NULL,
  `options` VARCHAR(250),
  `date` VARCHAR(10)  NULL,
  `explanation` VARCHAR(1000),
  `text_Area` VARCHAR(10)  NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
-- -----------------------------------------------------
-- Table `etafakna`.` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_AR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_AR` VARCHAR(100)  NULL,
  `part2_AR` VARCHAR(50) NULL,
  `inputType` LONGTEXT  NULL,
  `options` VARCHAR(250),
  `date` VARCHAR(10)  NULL,
  `explanation` VARCHAR(1000),
  `text_Area` VARCHAR(10)  NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(50) NULL,
  `contracts_id` INT NOT NULL,
  `contracts_contract_types_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (
    `id`,
    `contracts_id`,
    `contracts_contract_types_id`,
    `questions_id`
  ),
  INDEX `fk_answers_questions2_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions2` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions_FR` (`id`)  ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`questions_has_contract_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_has_contract_types_EN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `contract_types_id` INT NOT NULL,
  `order_question` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_has_contract_types_questions_EN` (`questions_id` ASC) VISIBLE,
  INDEX `fk_questions_has_contract_types_contract_types0` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_contract_types_contract_types0` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_questions_has_contract_types_questions_EN` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`questions_has_contract_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_has_contract_types_FR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `contract_types_id` INT NOT NULL,
  `order_question` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_has_contract_types_questions_FR` (`questions_id` ASC) VISIBLE,
  INDEX `fk_questions_has_contract_types_contract_types2` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_contract_types_contract_types2` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_questions_has_contract_types_questions_FR` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`questions_has_contract_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_has_contract_types_AR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `contract_types_id` INT NOT NULL,
  `order_question` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_has_contract_types_questions_AR` (`questions_id` ASC) VISIBLE,
  INDEX `fk_questions_has_contract_types_contract_types3` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_contract_types_contract_types3` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_questions_has_contract_types_questions_AR` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `username` VARCHAR(200) ,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `address` VARCHAR(200) ,
  `phone` VARCHAR(200) NOT NULL,
  `role` VARCHAR(200) NOT NULL,
  `image` VARCHAR(200),
  `status` VARCHAR(200) NOT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  `notification` VARCHAR(200) NULL DEFAULT NULL,
  `signatureUrl` VARCHAR(200) NULL DEFAULT NULL,
  `carteCinFront` VARCHAR(200) NULL DEFAULT NULL,
  `carteCinBack` VARCHAR(200) NULL DEFAULT NULL,
  `faceVideo` VARCHAR(200) NULL DEFAULT NULL,
  `scanSignature` VARCHAR(200) NULL DEFAULT NULL,
  `scanSignatureCheck` VARCHAR(200) NULL DEFAULT false,
  `formulaireCheck` VARCHAR(200) NULL DEFAULT false,
  `CINCheck` VARCHAR(200) NULL DEFAULT false,
  `videiSelfieCheck` VARCHAR(200) NULL DEFAULT false,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`users_has_contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`users_has_contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `contracts_id` INT NOT NULL,
  `receiver` INT NULL DEFAULT NULL,
  `receiver_email` VARCHAR(45) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_contracts_contracts1_idx` (`contracts_id` ASC) VISIBLE,
  INDEX `fk_users_has_contracts_users1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_contracts_contracts1` FOREIGN KEY (`contracts_id`) REFERENCES `etafakna`.`contracts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_users_has_contracts_users1` FOREIGN KEY (`owner`) REFERENCES `etafakna`.`users` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`users_has_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`users_has_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `contracts_id` INT NOT NULL,
  `receiver` INT NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `seen` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_notification_contracts1_idx` (`contracts_id` ASC) VISIBLE,
  INDEX `fk_users_has_notification_users1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_notification_notification` FOREIGN KEY (`contracts_id`) REFERENCES `etafakna`.`contracts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_users_has_notification_users1` FOREIGN KEY (`owner`) REFERENCES `etafakna`.`users` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- insert questions 
INSERT INTO etafakna.questions_AR(content_AR,part2_AR,inputType,options,date,explanation,text_Area)
VALUES

-- Attestation de stage
(N'اسم و لقب  ',N' صاحب/ة الشركة',null,null,"false",null,"null"),
(N'عدد بطاقة التعريف الوطنية',N'صاحب/ة الشركة',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف ',N'صاحب/ة الشركة',null,null,"true",null,"null"),
(N'اسم الشركة ',NULL,null,null,"false",null,"null"),
(N'مقر الشركة',NULL,null,null,"false",null,"null"),
(N'اسم و لقب  ',N'المتربص/ة',null,null,"false",null,"null"),
(N'عدد بطاقة التعريف الوطنية',N'المتربص/ة',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف ',N'المتربص/ة',null,null,"true",null,"null"),
(N'اختصاص التربص ',null,null,null,"false",null,"null"),
(N'مدة التربص',N'بالأشهر',null,null,"false",null,"null"),
(N'بداية فترة التربص',null,null,null,"true",null,"null"),
(N'نهاية فترة التربص',null,null,null,"true",null,"null"),
(N'تاريخ الامضاء  ',null,null,null,"true",null,"null"),

-- CDD
(N'اسم الشركة المؤجرة',null,null,null,"false",null,"null"),
(N'المقر الاجتماعي للشركة',null,null,null,"false",null,"null"),
(N'اسم و لقب ',N'الممثل القانوني للشركة',null,null,"false",null,"null"),
(N'اسم و لقب ',N'الأجير/ة',null,null,"false",null,"null"),
(N'جنسية ',N'الأجير/ة',null,'civilite',"false",null,"null"),
(N'مكان ولادة',N'الأجير/ة',null,null,"false",null,"null"),
(N'رقم بـطـاقـة التعريف الـوطنيـة',N'الأجير/ة',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف',N'الأجير/ة',null,null,"true",null,"null"),
(N'عنوان ',N'الأجير/ة',null,null,"false",null,"null"),
(N'المنصب المشغور في العمل ',null,null,null,"false",null,"null"),
(N'مـدة العمل ',N'بالأشهر',null,null,"false",null,"null"),
(N'بداية من ',null,null,null,"true",null,"null"),
(N'الى غاية  ',null,null,null,"true",null,"null"),
(N'الأجـر الشهري ',null,null,null,"false",null,"null"),
(N'فترة التجربة المحددة  ',N'بالاشــهـر',null,null,"false",null,"null"),
(N'تاريخ امضاء العقد  ',null,null,null,"true",null,"null"),

-- CDI
(N'اسم الشركة المؤجرة',null,null,null,"false",null,"null"),
(N'المقر الاجتماعي للشركة',null,null,null,"false",null,"null"),
(N'اسم و لقب ',N'الممثل القانوني للشركة',null,null,"false",null,"null"),
(N'اسم و لقب ',N'الأجير/ة',null,null,"false",null,"null"),
(N'رقم بـطـاقـة التعريف الـوطنيـة',N'الأجير/ة',null,null,"false",null,"null"),
(N'عنوان ',N'الأجير/ة',null,null,"false",null,"null"),
(N'المنصب المشغور في العمل ',null,null,null,"false",null,"null"),
(N'الأجـر الشهري ',null,null,null,"false",null,"null"),
(N'مكان العمل',null,null,null,"false",null,"null"),
(N'تاريخ بداية تنفيذ العقد',null,null,null,"true",null,"null"),
(N'فترة التجربة المحددة  ',N'بالاشــهـر',null,null,"false",null,"null"),
(N'تاريخ امضاء العقد  ',null,null,null,"true",null,"null"),

-- loc dahabitation
(N'اسم و لقب ',N'المالك',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'المالك',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المالك',null,null,"true",null,"null"),
(N'اسم و لقب ',N'المتسوغ',null,null,"false",null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"true",null,"null"),
(N'عنوان  المحل الموضوع الكراء ',null,null,null,"false",null,"null"),
(N'عدد غرف المحل ',null,null,null,"false",null,"null"),
(N'مدة الكراء',N'بالاشــهـر',null,null,"false",null,"null"),
(N'بداية من',null,null,null,"true",null,"null"),
(N' إلى تاريخ ',null,null,null,"true",null,"null"),
(N' معين الكراء الشهري',null,null,null,"false",null,"null"),
(N' قيمة الضمان',null,null,null,"false",null,"null"),
(N' مكان الامضاء',null,null,null,"false",null,"null"),
(N'تاريخ الامضاء',null,null,null,"true",null,"null"),

-- loc commercial 
(N'اسم و لقب ',N'المالك',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'المالك',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المالك',null,null,"true",null,"null"),
(N'اسم و لقب ',N'المتسوغ',null,null,"false",null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"true",null,"null"),
(N'عنوان  المحل الموضوع الكراء ',null,null,null,"false",null,"null"),
(N'مساحة المحل ',N'بالمتر المربع ',null,null,"false",null,"null"),
(N'النشاط التجاري الذي سيتم تعاطيه في المحل',null,null,null,"false",null,"null"),
(N'مدة الكراء',N'بالاشــهـر',null,null,"false",null,"null"),
(N'بداية من',null,null,null,"true",null,"null"),
(N' إلى تاريخ ',null,null,null,"true",null,"null"),
(N' معين الكراء الشهري',null,null,null,"false",null,"null"),
(N' قيمة الضمان',null,null,null,"false",null,"null"),
(N' مكان الامضاء',null,null,null,"false",null,"null"),
(N'تاريخ الامضاء',null,null,null,"true",null,"null"),

-- loc dengagement 
(N'اسم و لقب ',N' القائم بالالتزام',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'المالك',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N' القائم بالالتزام',null,null,"true",null,"null"),
(N'عنوان',N' القائم بالالتزام',null,null,"false",null,"null"),
(N'موضوع الالتزام بالتفصيل',null,null,null,"false",null,null),
(N'تاريخ تعمير الاستمارة ',null,null,null,"true",null,"null"),

-- atte honneur 
(N'اسم و لقب ',N' القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N' القائم بالتصريح',null,null,"true",null,"null"),
(N' عنوان سكنى',N' القائم بالتصريح',null,null,"false",null,"null"),
(N' التصريحب التفصيل',null,null,null,"false",null,null),
(N' تاريخ التصريح',null,null,null,"true",null,null),

-- atte domiciel 
(N'اسم و لقب ',N' القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N' القائم بالتصريح',null,null,"true",null,"null"),
(N' اسم الشركة',null,null,null,"false",null,"null"),
(N' نوع الشركة',null,null,null,"false",null,"null"),
(N' رأسمال الشركة',null,null,null,"false",null,"null"),
(N' العنوان',null,null,null,"false",null,"null"),
(N' مقابل الاقامة ',null,null,null,"false",null,"null"),
(N' تاريخ تعمير الاستمارة  ',null,null,null,"true",null,"null"),

-- freelance normal person
(N'اسم و لقب ',N' المؤجر/ة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' للمؤجر/ة ',null,null,"false",null,"null"),
(N'اسم و لقب ',N' منفذ/ة العمل الحر',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' منفذ/ة العمل الحر ',null,null,"false",null,"null"),
(N' مجال العمل الحرّ',null,null,null,"false",null,"null"),
(N' تحديد العمل موضوع العقد بالتفصيل',null,null,null,"false",null,"null"),
(N'المدة التي سيمتد خلالها العمل الحر',N'بالاشــهـر',null,null,"false",null,"null"),
(N'المقابل  ',N'بالدينار التونسي',null,null,"false",null,"null"),
(N'تاريخ آخر أجل للخلاص ',null,null,null,"true",null,"null"),
(N' تاريخ إجراء الامضاء ',null,null,null,"true",null,"null"),

-- freelance company
(N' اسم الشركة ' ,N' المؤجر/ة',null,null,"false",null,"null"),
(N' اسم ولقب ' ,N'من سيمثل الشركة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'من سيمثل الشركة ',null,null,"false",null,"null"),
(N'اسم و لقب ',N' منفذ/ة العمل الحر',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' منفذ/ة العمل الحر ',null,null,"false",null,"null"),
(N' مجال العمل الحرّ',null,null,null,"false",null,"null"),
(N' تحديد العمل موضوع العقد بالتفصيل',null,null,null,"false",null,"null"),
(N'المدة التي سيمتد خلالها العمل الحر',N'بالاشــهـر',null,null,"false",null,"null"),
(N'المقابل  ',N'بالدينار التونسي',null,null,"false",null,"null"),
(N'تاريخ آخر أجل للخلاص ',null,null,null,"true",null,"null"),
(N' تاريخ إجراء الامضاء ',null,null,null,"true",null,"null"),

-- achat de voiture
(N'اسم و لقب ',N'بائع/ة السيارة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'بائع/ة السيارة ',null,null,"false",null,"null"),
(N' مقر سكنى',N'بائع/ة السيارة ',null,null,"false",null,"null"),
(N'اسم و لقب ',N' مشتري/ة السيارة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' مشتري/ة السيارة ',null,null,"false",null,"null"),
(N' مقر سكنى',N' مشتري/ة السيارة ',null,null,"false",null,"null"),
(N' صانع السيارة ',null ,null,null,"false",N'المصنع اي علامة السيارة كان تكون مرسيدس / بيجو …',"null"),
(N'نوع السيارة ',null ,null,null,"false",null,"null"),
(N'العدد الرتبي بالمصنع ',null ,null,null,"false",null,"null"),
(N'القوة المقدرة ',N'بالحصان' ,null,null,"false",null,"null"),
(N'وقود السيارة  ',null ,null,null,"false",null,"null"),
(N'تاريخ أول إذن بالجولان  ',null ,null,null,"true",null,"null"),
(N'رقم التسجيل للسيارة  ',null ,null,null,"false",null,"null"),
(N'ثمن بيع السيارة  ',N'بالدينار التونسي' ,null,null,"false",null,"null"),
(N'تاريخ تحرير العقد  ',null ,null,null,"true",null,"null"),

-- vente 
(N'اسم ولقب ',N'البائع/ة' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'البائع/ة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'البائع/ة' ,null,null,null,null,"null"),
(N'اسم ولقب ',N'المشتري/ة' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'المشتري/ة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'المشتري/ة' ,null,null,null,null,"null"),
(N'موضوع عقد البيع و وصفه ',null ,null,null,null,null,"null"),
(N'ثمن البيع  ',N'بالدينار التونسي' ,null,null,null,null,"null"),
(N'تاريخ تحرير العقد  ',N'بالدينار التونسي' ,null,null,"true",null,"null"),

-- demande officiel 
(N'موضوع المطلب ',null ,null,null,null,null,"null"),
(N'اسم ولقب ',N'القائم/ة بالمطلب' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'القائم/ة بالمطلب' ,null,null,null,null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'القائم/ة بالمطلب',null,null,"true",null,"null"),
(N' عنوان سكنى',N'القائم/ة بالمطلب',null,null,"false",null,"null"),
(N' صفة القائم بالمطلب',null,null,null,"false",N'طالب اذا كان المطلب موجه الى ادارة الكلية او موظف في الشركة اذا المطلب موجه للشركة الموظفة او ولي امر التلميذ/ة , بالنسبة للمدرسة او المعهد…',"null"),
(N'الهيكل أو صفة الشخص المسؤول ',N'المطلوب منه',null,null,"false",N' تحديد الطرف الموجه له المطلب: مثلا عميدة كلية العلوم بتونس, او المدير التنفيذي للبنك , او وزارة التربية والتعليم…',"null"),
(N' موضوع المطلب بالتفصيل',null,null,null,"false",null,"null"),
(N' تاريخ  تحرير المطلب ',null,null,null,"true",null,"null"),

-- procuration 
(N'اسم ولقب ',N'الموكل' ,null,null,null,N'الشخص اللي بش يعطيك التوكيل وبش تاخو بلاصتو',"null"),
(N'رقم بطاقة التعريف  ',N'الموكل' ,null,null,null,null,"null"),
(N'صفة الموكل',null ,null,null,null,null,"null"),
(N'اسم ولقب ',N'الوكيل' ,null,null,null,N'الشخص اللي بش يقوم بالتوكيل يعني اللي بش يقضي هو القضية في بلاصت العبد الآخر',"null"),
(N'رقم بطاقة تعريف',N'الوكيل ' ,null,null,null,null,"null"),
(N'الغرض من التوكيل',null ,null,null,null,N'مثلا لتمثيلي امام البلدية او لتمثيلي امام المجلس كذا كذا او امام الوزارة كذا كذا…',"null"),

-- CIVP
(N'اسم المؤسسة',null ,null,null,null,null,"null"),
(N'قطاع نشاط المؤسسة',null ,null,null,null,null,"null"),
(N' البريد الألكتروني للمؤسسة',null ,null,null,null,null,"null"),
(N' المقر الإجتماعي للمؤسسة',null ,null,null,null,null,"null"),
(N' المعرف الجبائي للمؤسسة',null ,null,null,null,null,"null"),
(N' رقم الانخراط بالصندوق الوطني للضمان االجتماعي للمؤسسة',null ,null,null,null,null,"null"),
(N'اسم ولقب',N'رئيس المؤسسة' ,null,null,null,null,"null"),
(N'اسم ولقب',N'الممثل القانوني للمؤسسة' ,null,null,null,null,"null"),
(N'اسم ولقب',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'مكان ولادة ',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'تاريخ ولادة ',N'المنتفع/ة' ,null,null,"true",null,"null"),
(N'رقم بطاقة التعريف الوطنية',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'عنوان ',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'البريد الالكتروني',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'المستوى التعليمي ',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'الاختصاص',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'الشهادة التي تحصل عليها',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'تاريخ الحصول على الشهادة',N'المنتفع/ة' ,null,null,"true",null,"null"),
(N'الحساب الجاري',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'فرع البنك أو مكتب البريد',null ,null,null,null,null,"null"),
(N'المنصب المشغور في العمل',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'اسم ولقب',N'المؤطر/ة للمنتفع/ة' ,null,null,null,null,"null"),
(N'صفة المؤطر/ة بالمؤسسة',null ,null,null,null,null,"null"),
(N'المقر الذي يجري فيه العمل',null ,null,null,null,null,"null"),
(N'تاريخ بداية عقد العمل',null ,null,null,"true",null,"null"),
(N'تاريخ نهاية عقد العمل ',null ,null,null,"true",null,"null"),
(N'المنحة الشهرية المتحصل عليها من قبل الوكالة الوطنية للتشغيل والعمل المستقل',N'بالدينار' ,null,null,null,null,"null"),
(N'المنحة الشهرية المتحصل عليها مباشرة من المشغل',N'بالدينار' ,null,null,null,null,"null"),
(N'تاريخ تحرير العقد',null ,null,null,"true",null,"null"),

-- NDA
(N'اسم ولقب',N'صاحب المعلومة',null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'صاحب المعلومة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'صاحب المعلومة' ,null,null,null,null,"null"),
(N'اسم المؤسسة المعنية بالمعلومات',null ,null,null,null,null,"null"),
(N'اسم ولقب',N'متلقي/ة المعلومة',null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'متلقي/ة المعلومة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'متلقي/ة المعلومة' ,null,null,null,null,"null"),
(N'تحديد مدة الاتفاقية ',N' بالسنوات' ,null,null,null,null,"null"),

-- Pret_entre_parti
(N'اسم ولقب ',N'المقرض' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'المقرض' ,null,null,null,null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المقرض',null,null,"true",null,"null"),
(N'اسم ولقب ',N'المقترض' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'المقترض' ,null,null,null,null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المقترض',null,null,"true",null,"null"),
(N'مبلغ القرض ',N'بالدينار التونسي' ,null,null,null,null,"null"),
(N'تاريخ آخر أجل لتسديد ال‍دين',null,null,null,"true",null,"null"),
(N' مكان العقد',null,null,null,"false",null,"null"),
(N'تاريخ العقد',null,null,null,"true",null,"null");


INSERT INTO etafakna.questions_FR(content_FR,part2_FR,inputType,options,date,explanation,text_Area)
VALUES

-- DEMANDE OFFICIEL
("A l'attention",N'Civilité du destinataire',null,"civilite","false",null,"nukk"),
(N'Nom et prénom',N'Du destinataire',null,null,"false",null,"nukk"),
(N'Quel est l’objet de votre demande',null,null,null,"false",null,"nukk"),
(N'Veuillez préciser votre demande',null,null,null,"false",null,"textArea"),
(N'Fait à',N'Veuillez préciser votre gouvernorat',null,null,"false",null,null),
("Date de la demande",null,null,null,"true",null,null),
(N'Votre nom et prénom',"Du demandeur",null,null,"false",null,null),

-- CDD
(N'Nom de la société',null,null,null,null,"prrrrrrr",null),
(N'Activité de la société',null,null,null,null,null,null), 
(N'Adresse de la société',null,null,null,null,null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Civilité',N'Du gérant',"n","civilite","n",null,null),
(N'Nom et prénom',N'Du gérant(e)',"n","n","n",null,null),
(N'Civilité',N'De l’employé',"n","civilite","n",null,null),
(N'Nom et prénom',N'De l’employé',"n","n","n",null,null),
("Statut",N'De l’employé',"n","status","n",null,null),
("Lieu de naissance",null,"n","n","n",null,null),
("Date de naissance",null,"n","n","true",null,null),
(N'Numéro de la carte d identité',null,"n","n","n",null,null),
(N'CIN délivrée le',null,"n","n","true",null,null),
(N'Adresse',N'De l’employé',"n","n","n",null,null),
("Fonction",N'De l’employé',"n",null,null,null,null),
(N'Début du contrat',null,null,null,"true",null,null),
("Fin du contract",null,null,null,"true",null,null),
("Salaire mensuel","En dinars",null,null,null,null,null),
(N'Fait à',null,null,null,null,null,null),
("Date du contract",null,null,null,"true",null,null),

-- CONTRACT DE LOCATION A USAGE Bureau
(N'Civilité',"Le bailleur",null,"civilite",null,null,null),
("Nom et prénom du propriétaire","Le bailleur",null,null,"false",null,null),
(N'Civilité',"Le locataire",null,"civilite",null,null,null),
(N'Nom et prénom',"Le locataire",null,null,"false",null,null),
(N'Type de propriété',null,null,null,"false",null,null),
(N'Adresse de la propriété',"Rue, gouvernorat et code postal",null,null,"false",null,null),
(N'Durée de la location',null,null,null,"false",null,null),
(N'Location à partir de',null,null,null,"true",null,null),
(N'Jusqu’à',null,null,null,"true",null,null),
("Montant du loyer","En dinars",null,null,"false",null,null),
("Contrat fait à",null,null,null,"false",null,null),
("Date du contrat",null,null,null,"true",null,null),

-- CONTRACT DE LOCATION  à usage d'habitation
(N'Civilité',"Le propriétaire",null,"civilite",null,null,null),
(N'Entrez le nom et prénom',N'Le propriétaire',null,null,null,null,null),
(N'Demeurant à',N'Le propriétaire: Rue,gouvernorat et code postal',null,null,null,null,null),
(N'N° de la CIN',N'Le propriétaire',null,null,null,null,null),
(N'CIN délivrée le',N'Le propriétaire',null,null,null,null,null),
(N'Civilité',"Le locataire",null,"civilite",null,null,null),
(N'Entrez le nom et prénom',"Le locataire",null,null,null,null,null),
(N'Entrez la nationalité',"Le locataire",null,null,null,null,null),
(N'Date de naissance',"Le locataire","true",null,"true",null,null),
(N'N° de la CIN',"Le locataire",null,null,null,null,null),
(N'CIN délivrée le',"Le locataire","true",null,"true",null,null),
(N'Demeurant à',"Le locataire: Rue,gouvernorat et code postal",null,null,null,null,null),
(N'Décrivez le type de propriété',null,null,"typeproprite",null,null,null),
(N'Adresse de la propriété',N'Rue,gouvernorat et code postal',null,null,null,null,null),
(N'Durée de la location',null,null,null,null,null,null),
(N'Date de début de la location',null,"true",null,"true",null,null),
(N'Date de fin de la location',null,"true",null,"true",null,null),
(N'Montant de la location',"En dinars",null,null,null,null,null),
(N'Location est ',null,null,"jour",null,null,null),
(N'Montant du cautionnement en TND',"En dinars",null,null,null,null,null),
(N'Prise en charge des consommations (eau/électricité) par',null,null,"locprop",null,null,null),
(N'Date du contrat',null,"true",null,"true",null,null),

-- CONTRACT DENGAGEMENT
(N'Civilité',N'De l’engagé(e)',null,"civilite","n",null,null),
(N'Nom et prénom',N'De l’engagé(e)',null,null,"false",null,null),
(N'Numéro de CIN',null,null,null,null,null,null),
(N'CIN délivrée le',null,null,null,"true",null,null),
(N'Indiquer la fonction',N'De l’engagé(e)',null,null,null,null,null),
(N'Nom de ma société',null,null,null,null,null,null),
(N'Identifiant unique',null,null,null,null,null,null),
(N'Je m`engage',null,null,null,null,null,null),
(N'Fait le',null,null,null,"true",null,null),
(N'Fait à',null,null,null,null,null,null),

-- Contrat de Domiciliation
(N'Nom et prénom',null,null,null,"false",null,null),
(N'Numéro de carte CIN',null,null,null,null,null,null),
(N'CIN délivrée le',null,null,null,"true",null,null),
(N'Raison social',N'Nom de la société',null,null,null,null,null),
(N'Forme juridique',null,null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,null,null,null,null),
(N'Adress du siège',null,null,null,null,null,null),
(N'À titre',null,null,"titre",null,null,null),
(N'Fait à',null,null,null,null,null,null),
(N'Fait le',null,null,null,"true",null,null),

-- Contrat de attestation de stage
(N'Civilité',"Employeur","civilite","civilite",null,null,null),
(N'Nom et prénom',"Employeur",null,null,null,null,null),
(N'Indiquer le fonction dans l’entreprise',"Employeur",null,null,null,null,null),
(N'Civilité',"Stagiare",null,"civilite",null,null,null),
(N'Nom et prénom',"Stagiare",null,null,null,null,null),
(N'Adresse du Stagiare',N'Rue, gouvernorat et code postal',null,null,null,null,null),
(N'Nom de l’entreprise',null,null,null,null,null,null),
(N'Date du début de stage',null,"true",null,"true",null,null),
(N'Date de fin du stage',null,"true",null,"true",null,null),
(N'Indiquer le poste dans l’entreprise',"Stagiaire",null,null,null,null,null),
(N'Fait le',null,null,null,"true",null,null),

-- Contract Devis Facture
(N'Quel est le nom de votre Société ?',null,null,NULL,null,null,null),
(N'Quel est votre gouvernorat ?',null,null,NULL,null,null,null),
(N'Quel est la date de votre facture ?',null,null,NULL,"true",null,null),
(N'Quel est le nom de la société de votre client ?',null,null,NULL,null,null,null),
(N'Quel est la Matricule Fiscale de votre client ?',null,null,NULL,null,null,null),
(N'Quel est le numéro de votre facture ?',null,null,NULL,null,null,null),
(N'Quel est l’année de la facture ?',null,null,NULL,null,null,null),
(N'Insérez le nom de votre produit ?',null,null,NULL,null,null,null),
(N'Insérez la quantité de ce produit?',null,null,NULL,null,null,null),
(N'Insérez le prix du produit',null,null,NULL,null,null,null),
(N'Quel est l’adresse de votre société?',null,null,NULL,null,null,null),
(N'Quel est la Matricule Fiscale de votre société ?',null,null,NULL,null,null,null),
(N'Quel est votre code postale',null,null,NULL,null,null,null),
(N'Quel est la somme de la facture',null,null,null,null,null,null),
(N'Quelle est les nombre des Produit',null,null,null,null,null,null),

-- CIVP 
(N'Nom de la société',null,null,null,null,null,null),
(N'Activité de la société ',null,null,null,null,null,null),
(N'Adresse de la société ',N'Rue',null,null,null,null,null),
(N'Adresse de la société ',N'Gouvernorat',null,null,null,null,null),
(N'Adresse de la société ',N'Pays',null,null,null,null,null),
(N'Adresse de la société ',N'Code Postal',null,null,null,null,null),
(N'Adresse électronique',null,null,null,null,null,null),
(N'Numéro de téléphone',null,null,null,null,null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Numéro d’affiliation CNSS',null,null,null,null,null,null),
(N'Civilité ',N'Du gérant(e) ',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du gérant(e)',null,null,null,null,null),
(N'Civilité ',N'Du représentant',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du remplaçant',null,null,null,null,null),
(N'En qualité de :',N'Du remplaçant',null,null,null,null,null),
(N'Numéro de téléphone ',N'Du représentant',null,null,null,null,null),
(N'Civilité ',N'Du bénéficiaire ',null,"civilite",null,null,null),
(N'Nom et prénom',N'Bénéficaire du CIVP',null,null,null,null,null),
(N'Date de naissance',N'Bénéficaire du CIVP',null,null,"true",null,null),
(N'Lieu de naissance',N'Bénéficaire du CIVP',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Rue',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Gouvernorat',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Pays',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Code Postal',null,null,null,null,null),
(N'Adresse électronique',N'Bénéficiare',null,null,null,null,null),
(N'Niveau scolaire ',N'Bénéficiare',null,null,null,null,null),
(N'Diplôme & specialité',N'Bénéficiare',null,null,null,null,null),
(N'Date d’obtention du diplôme',null,null,null,"true",null,null),
(N'N°du compte courant',null,null,null,null,null,null),
(N'Agence bancaire ou postale',null,null,null,null,null,null),
(N'Poste occupé',N'bénéficiare',null,null,null,null,null),
(N'Durée du contrat ',"Du",null,null,"true",null,null),
(N'Durée du contrat ',"Au",null,null,"true",null,null),
(N'Salaire mensuel',N'En dinars',null,null,null,null,null),
(N'Fait à ',null,null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- Procuration 
(N'Civilité ',N'Du Mandataire ',null,"civilite",null,N'C’est la personne qui donne la procuration',null),
(N'Nom et Prénom ',N'Du Mandataire ',null,null,null,N'C’est la personne qui donne la procuration',null),
(N'Numéro de la carte CIN',N'Du Mandataire ',null,null,null,N'C’est la personne qui donne la procuration',null),
(N'Date de délivrance de la carte CIN',N'Du Mandataire ',null,null,"true",N'C’est la personne qui donne la procuration',null),
(N'Veuillez précisez la qualité du mandat',null,null,null,null,null,null),
(N'Civilité',N'Personne qui va effectuer la procuration',null,"civilite",null,N'C’est la personne qui accepte d’effectuer la procuration',null),
(N'Nom et Prénom',N'Personne qui va effectuer la procuration',null,null,null,N'C’est la personne qui accepte d’effectuer la procuration',null),
(N'Nom de l’entité ou l’organisme auprés duquel sera effectué la procuration',null,null,null,null,null,null),
(N'Date de la demande',null,null,null,"true",null,null),
(N'Précisez le lieu de la demande',null,null,null,null,null,null),

-- freelance
(N'Civilité ',N'Du freelanceur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du freelanceur',null,null,null,null,null),
(N'N° de la CIN',N'Du freelanceur',null,null,null,null,null),
(N'CIN délivrée le',N'Du freelanceur',null,null,"true",null,null),
(N'Précisez le domaine de connaissance',N'Du freelanceur',null,null,null,null,null),
(N'Civilité',N'Du client',null,N'civilite',null,null,null),
(N'Nom et prénom',N'Du client',null,null,null,null,null),
(N'Fonction',N'Du client',null,null,null,N'exemple: gérant(e) / responsable departement commerciale de la société XYZ…',null),
(N'Précisez la mission du freelanceur',null,null,null,null,null,null),
(N'Précisez la durée De la mission ',null,null,null,null,"exemple: 15 jours ou 3 mois",null),
(N'Montant de la rémunération',N'En dinars',null,null,null,null,null),
(N'Date limite du paiement Agenda ',null,null,null,"true",null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- Contrat d’achat et de vente
(N'Civilité ',N'Du vendeur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du vendeur',null,null,null,null,null),
(N'N° de la CIN',N'Du vendeur',null,null,null,null,null),
(N'Civilité ',N'De l’acheteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'De l’acheteur',null,null,null,null,null),
(N'N° de la CIN',N'De l’acheteur',null,null,null,null,null),
(N'Veuillez précisez le produit/objet acheté',null,null,null,null,null,null),
(N'Montant à payer',N'En dinars',null,null,null,null,null),
(N'Mentionnez la date du paiement ',null,null,null,"true",null,null),
(N'Date du contrat',null,null,null,"true",null,null),
(N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null,null),

-- Contrat de prêt d’argent entre particulier
(N'Civilité ',N'Du prêteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du prêteur',null,null,null,null,null),
(N'N° de la CIN',N'Du prêteur',null,null,null,null,null),
(N'Adresse du Prêteur',N'Rue, Gouvernorat et code postal',null,null,null,null,null),
(N'Civilité ',N'De l’emprunteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'De l’emprunteur',null,null,null,null,null),
(N'N° de la CIN',N'De l’emprunteur',null,null,null,null,null),
(N'Adresse du l’emprunteur',N'Rue, Gouvernorat et code postal',null,null,null,null,null),
(N'Veuillez écrire le montant du Prêt',N'En dinars',null,null,null,null,null),
(N'Date du versement du prêt',null,null,null,"true",null,null),
(N'Date du paiement du prêt',null,null,null,"true",null,null),
(N'Date du contrat',null,null,null,"true",null,null),
(N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null,null),

-- vente voiture
(N'Civilité ',N'Le vendeur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Le vendeur',null,null,null,null,null),
(N'N° de la CIN',N'Le vendeur',null,null,null,null,null),
(N'CIN délivrée le',N'Le vendeur',null,null,"true",null,null),
(N'Civilité ',N'L’acheteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'L’acheteur',null,null,null,null,null),
(N'N° de la CIN',N'L’acheteur',null,null,null,null,null),
(N'CIN délivrée le',N'L’acheteur',null,null,"true",null,null),
(N'Quel est le N° Immatriculation ',N'Du Véhicule à vendre',null,null,null,null,null),
(N'Précisez la date de la 1ère mise en circulation',N'Du Véhicule à vendre',null,null,"true",null,null),
(N'Caractéristiques de la voiture ',N'Précisez le genre',null,null,null,null,null),
(N'Caractéristiques de la voiture ',N'Précisez le marque ',null,null,null,null,null),
(N'Caractéristiques de la voiture ',N'Précisez le type',null,null,null,null,null),
(N'Veuillez écrire le numéro de serie du vehicule',null,null,null,null,null,null),
(N'Energie',null,null,null,null,null,null),
(N'Puissance',N'Par chevaux',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),
(N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null,null);



-- insert question-has-contracttype 
INSERT INTO etafakna.questions_has_contract_types_EN(questions_id, contract_types_id, order_question)
VALUES

   (1, 34, 1),
   (2, 34, 2),
   (3, 34, 3),
   (4, 34, 4),
   (5, 34, 1),
   (6, 19, 1);
 -- insert question-has-contracttype 


INSERT INTO etafakna.questions_has_contract_types_AR(questions_id, contract_types_id, order_question)
VALUES

-- attestation de stage
   (1,  3, 1),
   (2,  3, 2),
   (3,  3, 3),
   (4,  3, 4),
   (5,  3, 5),
   (6,  3, 6),
   (7,  3, 7),
   (8,  3, 8),
   (9,  3, 9),
   (10, 3, 10),
   (11, 3, 11),
   (12, 3, 12),
   (13, 3, 13),

  -- CDD
   (14, 17,1),
   (15, 17, 2),
   (16, 17, 3),
   (17, 17, 4),
   (18, 17, 5),
   (19, 17, 6),
   (20, 17, 7),
   (21, 17, 8),
   (22, 17, 9),
   (23, 17, 10),
   (24, 17, 11),
   (25, 17, 12),
   (26, 17, 13),
   (27, 17, 14),
   (28, 17, 15),
   (29, 17, 16),

-- CDI
   (30, 16,1),
   (31, 16, 2),
   (32, 16, 3),
   (33, 16, 4),
   (34, 16, 5),
   (35, 16, 6),
   (36, 16, 7),
   (37, 16, 8),
   (38, 16, 9),
   (39, 16, 10),
   (40, 16, 11),
   (41, 16, 12),

-- LOC dahabitation
   (42, 20, 1),
   (43, 20, 2),
   (44, 20, 3),
   (45, 20, 4),
   (46, 20, 5),
   (47, 20, 6),
   (48, 20, 7),
   (49, 20, 8),
   (50, 20, 9),
   (51, 20, 10),
   (52, 20, 11),
   (53, 20, 12),
   (54, 20, 13),
   (55, 20, 14),
   (56, 20, 15),

-- LOC commercial
   (57, 19,1),
   (58, 19, 2),
   (59, 19, 3),
   (60, 19, 4),
   (61, 19, 5),
   (62, 19, 6),
   (63, 19, 7),
   (64, 19, 8),
   (65, 19, 9),
   (66, 19, 10),
   (67, 19, 11),
   (68, 19, 12),
   (69, 19, 13),
   (70, 19, 14),
   (71, 19, 15),
   (72, 19, 16),

-- contract dengagement
   (73, 8,1),
   (74, 8, 2),
   (75, 8, 3),
   (76, 8, 4),
   (77, 8, 5),
   (78, 8, 6),

-- attes honneur
   (79, 11,1),
   (80, 11, 2),
   (81, 11, 3),
   (82, 11, 4),
   (83, 11, 5),
   (84, 11, 6),

-- con domiciel
   (85, 12,1),
   (86, 12, 2),
   (87, 12, 3),
   (88, 12, 4),
   (89, 12, 5),
   (90, 12, 6),
   (91, 12, 7),
   (92, 12, 8),
   (93, 12, 9),

-- freelance normal person
   (94,  25,1),
   (95,  25, 2),
   (96,  25, 3),
   (97,  25, 4),
   (98,  25, 5),
   (99,  25, 6),
   (100, 25, 7),
   (101, 25, 8),
   (102, 25, 9),
   (103, 25, 10),

 -- freelance company
   (104, 26,1),
   (105, 26, 2),
   (106, 26, 3),
   (107, 26, 4),
   (108, 26, 5),
   (109, 26, 6),
   (110, 26, 7),
   (111, 26, 8),
   (112, 26, 9),
   (113, 26, 10),
   (114, 26, 11),

   -- achat de voiture
   (115, 22,1),
   (116, 22,2),
   (117, 22,3),
   (118, 22,4),
   (119, 22,5),
   (120, 22,6),
   (121, 22,7),
   (122, 22,8),
   (123, 22,9),
   (124, 22,10),
   (125, 22,11),
   (126, 22,12),
   (127, 22,13),
   (128, 22,14),
   (129, 22,15),
   (130, 22,16),

-- vente sample 
   (131,7,1),
   (132,7,2),
   (133,7,3),
   (134,7,4),
   (135,7,5),
   (136,7,6),
   (137,7,7),
   (138,7,8),
   (139,7,9),

-- demande off
   (140, 14,1),
   (141, 14,2),
   (142, 14,3),
   (143, 14,4),
   (144, 14,5),
   (145, 14,6),
   (146, 14,7),
   (147, 14,8),
   (148, 14,9),

  -- procuration
   (149,15,1),
   (150,15,2),
   (151,15,3),
   (152,15,4),
   (153,15,5),
   (154,15,6),

-- CIVP
   (155, 18,1),
   (156, 18, 2),
   (157, 18, 3),
   (158, 18, 4),
   (159, 18, 5),
   (160, 18, 6),
   (161, 18, 7),
   (162, 18, 8),
   (163, 18, 9),
   (164, 18, 10),
   (165, 18, 11),
   (166, 18, 12),
   (167, 18, 13),
   (168, 18, 14),
   (169, 18, 15),
   (170, 18, 16),
   (171, 18, 17),
   (172, 18, 18),
   (173, 18, 19),
   (174, 18, 20),
   (175, 18, 21),
   (176, 18, 22),
   (177, 18, 23),
   (178, 18, 24),
   (179, 18, 25),
   (180, 18, 26),
   (181, 18, 27),
   (182, 18, 28),

   -- NDA
   (183, 2,1),
   (184, 2,2),
   (185, 2, 2),
   (186, 2, 3),
   (187, 2, 4),
   (188, 2, 5),
   (189, 2, 6),
   (190, 2, 7),

-- Pret_entre_parti
   (191, 4,1),
   (192, 4,2),
   (193, 4, 3),
   (194, 4, 4),
   (195, 4, 5),
   (196, 4, 6),
   (197, 4, 7),
   (198, 4, 8),
   (199, 4, 9),
   (200, 4, 10);



VALUES

-- Questions Demande Officielle
   (1, 14, 1),
   (2, 14, 2),
   (3, 14, 3),
   (4, 14, 4),
   (5, 14, 5),
   (6, 14, 6),
   (7, 14, 7),

-- CDD
   (8,  17, 1),
   (9,  17, 2),
   (10, 17, 3),
   (11, 17, 4),
   (12, 17, 5),
   (13, 17, 6),
   (14, 17, 7),
   (15, 17, 8),
   (16, 17, 9),
   (17, 17, 10),
   (18, 17, 11),
   (19, 17, 12),
   (20, 17, 13),
   (21, 17, 14),
   (22, 17, 15),
   (23, 17, 16),
   (24, 17, 17),
   (25, 17, 18),
   (26, 17, 19),
   (27, 17, 20),

-- CONTRACT DE LOCATION A USAGE Bureau
   (28, 19, 1),
   (29, 19, 2),
   (30, 19, 3),
   (31, 19, 4),
   (32, 19, 5),
   (33, 19, 6),
   (34, 19, 7),
   (35, 19, 8),
   (36, 19, 9),
   (37, 19, 10),
   (38, 19, 11),
   (39, 19, 12),

-- CONTRACT DE LOCATION  à usage d'habitation
   (40, 20, 1),
   (41, 20, 2),
   (42, 20, 3),
   (43, 20, 4),
   (44, 20, 5),
   (45, 20, 6),
   (46, 20, 7),
   (47, 20, 8),
   (48, 20, 9),
   (49, 20, 10),
   (50, 20, 11),
   (51, 20, 12),
   (52, 20, 13),
   (53, 20, 14),
   (54, 20, 15),
   (55, 20, 16),
   (56, 20, 17),
   (57, 20, 18),
   (58, 20, 19),
   (59, 20, 20),
   (60, 20, 21),
   (61, 20, 22),

-- CONTRACT DENGAGEMENT
  (62, 8, 1),
  (63, 8, 2),
  (64, 8, 3),
  (65, 8, 4),
  (66, 8, 5),
  (67, 8, 6),
  (68, 8, 7),
  (69, 8, 8),
  (70, 8, 9),
  (71, 8, 10),

-- Contrat de Domiciliation
  (72, 12, 1),
  (73, 12, 2),
  (74, 12, 3),
  (75, 12, 4),
  (76, 12, 5),
  (77, 12, 6),
  (78, 12, 7),
  (79, 12, 8),
  (80, 12, 9),
  (81, 12, 10),

-- Contrat de attestation de stage
  (82, 3, 1),
  (83, 3, 2),
  (84, 3, 3),
  (85, 3, 4),
  (86, 3, 5),
  (87, 3, 6),
  (88, 3, 7),
  (89, 3, 8),
  (90, 3, 9),
  (91, 3, 10),
  (92, 3, 11) ,

  -- Contract Devis Facture
  (93, 10, 1),
  (94, 10, 2),
  (95, 10, 3),
  (96, 10, 5),
  (97, 10, 6),
  (98, 10, 7),
  (99, 10, 8),
  (100,10, 10),
  (101,10, 11),
  (102,10, 12),
  (103,10, 13),
  (104,10, 14),
  (105,10, 15),
  (106,10, 16),
  (107,10, 17),

--  civp
  (108,18, 1),
  (109,18, 2),
  (110,18, 3),
  (111,18, 4),
  (112,18, 5),
  (113,18, 6),
  (114,18, 7),
  (115,18, 8),
  (116,18, 9),
  (117,18, 10),
  (118,18, 11),
  (119,18, 12),
  (120,18, 13),
  (121,18, 14),
  (122,18,  15),
  (123,18,  16),
  (124,18,  17),
  (125,18,  18),
  (126,18,  19),
  (127,18,  20),
  (128,18,  21),
  (129,18,  22),
  (130,18,  23),
  (131,18,  24),
  (132,18,  25),
  (133,18,  26),
  (134,18,  27),
  (135,18,  28),
  (136,18,  29),
  (137,18,  30),
  (138,18,  31),
  (139,18,  32),
  (140,18,  33),
  (141,18,  34),
  (142,18,  35),
  (143,18,  36),

  -- Procuration
  (144,15, 1),
  (145,15, 2),
  (146,15, 3),
  (147,15, 4),
  (148,15, 5),
  (149,15, 6),
  (150,15, 7),
  (151,15, 8),
  (152,15, 9),
  (153,15, 10),

-- freelance
  (154,13, 1),
  (155,13, 2),
  (156,13, 3),
  (157,13, 4),
  (158,13, 5),
  (159,13, 6),
  (160,13, 7),
  (161,13, 8),
  (162,13, 9),
  (163,13, 10),
  (164,13, 11),
  (165,13, 12),
  (166,13, 13),

-- vente et achat
  (167,7, 1),
  (168,7, 2),
  (169,7, 3),
  (170,7, 4),
  (171,7, 5),
  (172,7, 6),
  (173,7, 7),
  (174,7, 8),
  (175,7, 9),
  (176,7, 10),
  (177,7, 11),

-- Contrat de prêt d’argent entre particulier
   (178, 4, 1),
   (179, 4, 2),
   (180, 4, 3),
   (181, 4, 4),
   (182, 4, 5),
   (183, 4, 6),
   (184, 4, 7),
   (185, 4, 8),
   (186, 4, 9),
   (187, 4, 10),
   (188, 4, 11),
   (189, 4, 12),
   (190, 4, 13),

   -- vent voiture
   (191, 21, 1),
   (192, 21, 2),
   (193, 21, 3),
   (194, 21, 4),
   (195, 21, 5),
   (196, 21, 6),
   (197, 21, 7),
   (198, 21, 8),
   (199, 21, 9),
   (200, 21, 10),
   (201, 21, 11),
   (202, 21, 12),
   (203, 21, 13),
   (204, 21, 14),
   (205, 21, 15),
   (206, 21, 16),
   (207, 21, 17),
   (208, 21, 18);

-- Insert All Contracts
INSERT INTO
  etafakna.users(
    first_name,
    last_name,
    username,
    email,
    password,
    address,
    phone,
    role,
    image,
    status,
    created_at
  )
VALUES
(
    "fares",
    "fares",
    "fares",
    "faroussassg007@gmail.com",
    "$2b$10$sIzEhADNfPcEOUCO7ILtAunEbf8Y9YVQt2/gTaZ0TvHvNA3bN6U1O",
    "boumhale",
    "122883",
    "user",
    "https://res.cloudinary.com/dew6e8h2m/image/upload/v1664624355/cld-sample.jpg",
    "Activated",
    "2022-09-29"
  ),
  (
    "omar",
    "omar",
    "omar",
    "massoudiomar54321@gmail.com",
    "$2b$10$sIzEhADNfPcEOUCO7ILtAunEbf8Y9YVQt2/gTaZ0TvHvNA3bN6U1O",
    "Beja",
    "122883",
    "user",
    "https://res.cloudinary.com/dew6e8h2m/image/upload/v1664624356/cld-sample-3.jpg",
    "Activated",
    "2022-09-29"
  ),
  (
    "Norchen",
    "Mezni",
    "Norchen Mezni",
    "Norchenmezni1@gmail.com",
    "$2b$10$kzeiOtT.FvnFlD175KxSHe1VhrFJ.OUtIcq.5C4YprY6qjDvWz3/a",
    "Tunis",
    "52979979",
    "user",
    "null",
    "Activated",
    "2022-09-29"
  );




-- Insert All Contracts
INSERT INTO
  etafakna.contract_types(
    signed_time,
    time_answering,
    title_EN,
    title_FR,
    title_AR,
    description_FR,
    description_AR,
    description_EN,
    image_url,
    template_FR,
    template_AR,
    template_EN,
    country,
    types,
    categories,
    inside_categories
  )
VALUES 
(
   0,
    5,
    "Employment",
    "Travail",
    N'عقد التوظيف',
    "Anything can be rented using E-tafakna e-greement... From a room, to an appartement or a car...",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/travaille_y5oqzh.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "types",
    "categories",
    "null"
  ),
-- (
--     0,
--     5,
--     "Commercial rental",
--     "Location commercial",
--     N'عقد كراء محل تجاري',
--     "desc_fr",
--     "desc_AR",
--     "desc_EN",
--     "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/cdd_qmrm8e.png",
--     "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317354/5._Loc_commerciale_AR_ffffff_fzvxbe_wriymj.docx",
--     "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
--     "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
--     "Tunisia",
--     "types",
--     "categories",
--     "null"
--   ),
  (
0,
    5,
    "Nda",
    "NDA",
    N'اتفاق غير معلن',
    "This is Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670325480/New%20icons%20contracts/unnamed_bipsgv.png",
    "temp_FR",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670323620/15._NDA_AR_xlzy9t.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
0,
    5,
    "Training Certificate",
    "Attestation de stage",
    N'شهادة تربص',
    N'Lattestation de stage E-Tafakna, aussi appelée le certificat de stage, est un document remis au stagiaire permettant de valider une expérience professionnelle au sein de lentreprise.',
    "desc_AR",
    "In the broadest sense, a training certificate is a document certifying that the holder has taken a specific course of training.",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/stage_ignntm.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317565/Attestation-de-stage_n2_fffffffffffffffffffff_vskvis_1_os9fqw_imxrxt.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317650/_1._Attestation_Stage_AR_fffffff_vjv8jp_2_z3llel.docx",
    "null",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (0,
    5,
    "Microcredit",
    N'Prêt entre particuliers ',
    N'قرض بين الأفراد',
    "This is loan Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/pret_entre_particulier_vygdo9.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317786/16._Pret_entre_partic_FR_j86rzg_kjhioa.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670341104/16._Pret_entre_partic_AR_je3ftv.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
0,
    5,
    "Car",
    "Voiture",
    N' سيارة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/car_fh1tdl.png",
    "temp_FR",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "car",
    "null"
  ),
  (
   0,
    5,
    "Rental of real estate",
    "Location de biens",
    N'تأجير العقارات',
    N'Tout peut être loué en utilisant le contrat de location de E-Tafakna. Dune chambre, une villa, un appartement, à un bureau. Quil s&#39;agisse d`une location à court terme ou à long terme',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/location_de_bien_prywdl.png",
    "temple_FR",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "categorie",
    "null"
  ),
  (
0,
    5,
    "Sale and purchase",
    "Vente et Achat",
    N'بيع وشراء',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/Vente_Achat_duuhpn.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670318074/12._Vente___Achat_FR_lwlxxb_1_hb3rrh.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670318286/12.Vente_simple_AR_2_fiaul1_1_uilsqj.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1664737567/Template_Contrat_de_location_bureau_n3_xvsszr.docx",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
  0,
    5,
    N'Engagement',
    N'Engagement',
    N'التزام',
    N'Le contrat d’engagement E-Tafakna nous permet de nous assurer que vous soyez prêt à entreprendre des travaux, avant de commencer à travailler plus en profondeur sur votre projet.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/engagement_usouyg.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670318533/Engagement_contract_n2_x14mz3_wg8rm1_gukspl_1_ihtbkp_1_dnlbp0.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670319265/7._Engagement_fff_pduwtc_rhu0nk.docx",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665770960/WORD-CONTRACTS/Engagement_contract_n2_x14mz3_wg8rm1_gukspl.docx",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
 0,
    5,
    "Partnership",
    "Partenariat",
    N'عقد شراكة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/partenariat_ze8q6p.png",
    "temp_FR",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
0,
    5,
    "Quotation/Bill",
    "Devis/Facture ",
    N'فاتورة/devis',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308746/New%20icons%20contracts/Devis_facture_yg4aee.png",
    "https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "facture",
    "null"
  ),
  -- (
  --   0,
  --   5,
  --   "Travel insurance",
  --   "Assurance Voyage",
  --   N'تامين السفر',
  --   "This is Employment Contract Description",
  --   "desc_AR",
  --   "desc_EN",
  --   "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949430/icons/assurance_voyage_rrv8ql.png",
  --   "temp_FR",
  --   "temp_AR",
  --   "temp_EN",
  --   "Tunisia",
  --   "types",
  --   "null",
  --   "null"
  -- ),
  (
0,
    5,
    "Certificate of honor",
    N'Attestation sur l`honneur',
    N'تصريح على الشرف',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/decalaration_sur_lhonneur_ajcbuh.png",
    "temp_FR",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670319436/8._Attes_sur_l_honneur_AR_fffffff_x2vw0v_1_ofywd0.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  -- (
  --   0,
  --   5,
  --   "CV",
  --   "CV",
  --   N'أمر شراء',
  --   "This is Employment Contract Description",
  --   "desc_AR",
  --   "desc_EN",
  --   "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/exlusivite_fodbew.png",
  --   "temp_FR",
  --   "temp_AR",
  --   "temp_EN",
  --   "Tunisia",
  --   "types",
  --   "null",
  --   "null"
  -- ),
  (
 0,
    5,
    "Safe of real estate",
    "Domiciliation",
    N'شهادة في ايواء شركة',
    N'Le contrat de domiciliation E-Tafakna est une obligation pour toutes les sociétés, mais également pour les associations. Il sagit de ladresse administrative et fiscale à laquelle tous les courriers seront envoyés.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308746/New%20icons%20contracts/domicilation_lucacc.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670320593/Attestation_de_Domiciliation_n2_anigf5_yfnom4_1_eldxrc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670320688/6._Domiciliation_AR_1_ffff1_omhmkn_gxoxek.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
   (
0,
    5,
    "Freelancer",
    "Freelance",
  N'عقد عمل حر',
    "This is Freelancer Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/freelance_uydcui.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321152/6.Freelance_FR_1_j5qg7o_wtry5a.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321228/10._Freelance_AR_1_em839z_2_tzkeho.docx",
    "temp_EN",
    "Tunisia",
  "types",
    "freelance",
     "null"
  ),
  (
 0,
    5,
    "Official request",
    "Demande officielle",
    N'مطلب رسمي',
    N'Une demande Officielle E-Tafakna constitue effectivement une preuve réelle de la démarche engagée que l`on peut réaliser et apporter à toutes fins utiles.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308746/New%20icons%20contracts/demande_offficiel_kyzndt.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670320856/Demande_officielle_n4_m4cbe4_cfrc9c_1_u7vxsu.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670320922/9._Demande_AR_2_xvle6d_ftdfak.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
    
  ),
  (
0,
    5,
    "Power of attorney",
    "Procuration",
    N'توكيل',
    N'Desc_FR',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/procuration_nin84y.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670322351/10._Procuration_FR_753_2_rrzxje_cbvj41.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670322478/14._Procuration_AR_qhjo5o_1_glwp36.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
    0,
    5,
    "CDI",
    "CDI",
    N'عقد عمل غير محدد المدة',
    "CDI",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457759/unnamed_2_1_ztst4g.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321030/3._CDI_AR_fffff_ogzsix_1_cvtdw2.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "work",
    "categories",
    "inside_categories"
  ),
   

  (
    0,
    5,
    "CDD",
    "CDD",
    N'عقد عمل محدد المدة',
    N'Le contrat à durée déterminée (CDD) E-Tafakna est un contrat de travail par lequel un employeur recrute un salarié pour une durée limitée. Un tel contrat n’est possible que pour l’exécution d’une tâche précise et temporaire et seulement dans les cas énumérés par la loi.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457759/unnamed_2_1_ztst4g.png",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665748919/WORD-CONTRACTS/contract1_isna08_1_part1_esqffs_ycbrtu.docx,https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665748967/WORD-CONTRACTS/contract2_fiwvof_part2_i550oc_doi7zp.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321564/2._CDD_AR_fffff1_rgsynf_fgmpns.docx",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665748919/WORD-CONTRACTS/contract1_isna08_1_part1_esqffs_ycbrtu.docx,https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665748967/WORD-CONTRACTS/contract2_fiwvof_part2_i550oc_doi7zp.docx",
    "Tunisia",
    "work",
    "categories",
    "inside_categories"
  ),
  (
    0,
    5,
    "CIVP",
    "CIVP",
    N'عقد الإعداد للحياة المهنية',
    "CIVP",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457759/unnamed_2_1_ztst4g.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321638/5.2_CIVP_FR_niw0gv_6_k65laa_3_zfn3oi_gmeapc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321707/13._CIVP_AR_5_lshd1x_1_vvhcvn.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "work",
    "categories",
    "inside_categories"
  ),
  (
    0,
    5,
    "Rental of real estate",
    N'Location à usage de bureau',
    N'تأجير للاستخدام المكتبي',
    N'Tout peut être loué en utilisant le contrat de location de E-Tafakna. D`une chambre, une villa, un appartement, à un bureau. Qu`il s’agisse d`une location à court terme ou à long terme',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457757/unnamed_16_1_drpr0x.png",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665757549/WORD-CONTRACTS/location_1_yi45ht.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321887/location_2_c96htt_obgbc4.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321947/5._Loc_commerciale_AR_ffffff1_seykwm_ifejfv.docx",
    "temp_EN",
    "Tunisia",
    "work",
    "null",
    "inside_categorie"
  ),
  (
    0,
    5,
    "Rental of real estate",
    N'Location à usage d’habitation',
    N'عقد كراء محل سكني',
    N'Tout peut être loué en utilisant le contrat de location de E-Tafakna. D`une chambre, une villa, un appartement, à un bureau. Qu`il s’agisse d`une location à court terme ou à long terme',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457757/unnamed_16_1_drpr0x.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670322157/Contrat_de_location_simple_1_nsezaf_1_geahtf.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670322256/4._Loc_habitation_AR_ffff1_gbisrt_cacaf5.docx",
    "temp_EN",
    "Tunisia",
    "work",
    "null",
    "inside_categorie"
  ),
    (
    0,
    5,
    "Car sale",
    "Vente de voiture",
    N'عقد بيع سيارة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949430/icons/achat_voiture_j3ikzr.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317859/9._Vente_voiture_FR_nubcjp_6_oweo9r.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317991/11.Vente_voiture_AR_mwvqsr_ksuchi.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670244199/9._Vente_voiture_FR_nubcjp.docx",
    "Tunisia",
    "null",
    "categories",
    "car_categorie"
  ),
    (
    0,
    5,
    "Car sale",
    "Location de voiture",
    N'عقد كراء سيارة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949430/icons/achat_voiture_j3ikzr.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317859/9._Vente_voiture_FR_nubcjp_6_oweo9r.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317991/11.Vente_voiture_AR_mwvqsr_ksuchi.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670244199/9._Vente_voiture_FR_nubcjp.docx",
    "Tunisia",
    "null",
    "categories",
    "car_categorie"
  ),
    (
    0,
    5,
    "Quotation/Bill",
    "Devis ",
    N'فاتورة/التسعير',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/facture_devis_ox5oml.png",
    "https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "null",
    "categories",
    "facture"
  ),
    (
    0,
    5,
    "Quotation/Bill",
    "Devis ",
    N'فاتورة/التسعير',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/facture_devis_ox5oml.png",
    "https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "null",
    "categories",
    "facture"
  ),
    (
    0,
    5,
    "Normal person",
    "Personne normale",
  N'مستقل',
    "This is Freelancer Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949432/icons/freelance_zbfpcj.png",
    "temp_FR",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321228/10._Freelance_AR_1_em839z_2_tzkeho.docx",
    "temp_EN",
    "Tunisia",
   "freelance",
    "categories",
    "freelancee"
  ),
   (
    0,
    5,
    "Company",
    N'Société',
  N'مستقل',
    "This is Freelancer Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949432/icons/freelance_zbfpcj.png",
    "temp_FR",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321357/10._Freelance_AR_4_dkpgy7_cedcvw.docx",
    "temp_EN",
    "Tunisia",
    "freelance",
    "categories",
    "freelancee"
  );

-- INSERT INTO
--   etafakna.contract_types(
--     signed_time,
--     time_answering,
--     title_EN,
--     title_FR,
--     title_AR,
--     description_FR,
--     description_AR,
--     description_EN,
--     image_url,
--     template_FR,
--     template_AR,
--     template_EN,
--     country,
--     types,
--     categories,
--     inside_categories
--   )
-- VALUES
-- (
-- 0, 
-- 5, 
-- 'Facture', '
-- Facture', 
-- 'Facture', 'Facture', 
-- 'Facture', 
-- 'Facture', 
-- 'https://res.cloudinary.com/dn6kxvylo/image/upload/v1665584941/quotation_cx1xtp.png',
-- 'https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx',
-- 'https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx',
-- 'https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx',
-- 'tunisie', 
-- 'types',
-- NULL, 
-- NULL);
