SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema etafakna
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema etafakna
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `etafakna`;

CREATE SCHEMA IF NOT EXISTS `etafakna` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE `etafakna`;
-- -----------------------------------------------------
-- Table `etafakna`.`contract_types`
-- -----------------------------------------------------

 CREATE TABLE IF NOT EXISTS `etafakna`.`contract_types` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `signed_time` INT NULL DEFAULT NULL,
  `time_answering` INT NOT NULL,
  `title_EN` VARCHAR(200) NULL DEFAULT NULL,
  `title_FR` VARCHAR(200) NULL DEFAULT NULL,
  `title_AR` VARCHAR(200) NULL DEFAULT NULL,
  `description_EN` VARCHAR(1000) NULL DEFAULT NULL,
  `description_FR` VARCHAR(1000) NULL DEFAULT NULL,
  `description_AR` VARCHAR(1000) NULL DEFAULT NULL,
  `image_url` VARCHAR(200) NOT NULL,
  `template_EN` VARCHAR(1000) NULL DEFAULT NULL,
  `template_FR` VARCHAR(1000) NULL DEFAULT NULL,
  `template_AR` VARCHAR(1000) NULL DEFAULT NULL,
  `country` VARCHAR(10) NULL DEFAULT NULL,
  `types` VARCHAR(10) NULL DEFAULT NULL,
  `categories` VARCHAR(10) NULL DEFAULT NULL,
  `inside_categories` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB AUTO_INCREMENT = 18 DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

 ALTER TABLE `etafakna`.`contract_types` AUTO_INCREMENT = 1;


-- -----------------------------------------------------
-- Table `etafakna`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `contract_url` VARCHAR(1000) NOT NULL,
  `status` VARCHAR(50) NOT NULL,
  `created_at` VARCHAR(50) NULL DEFAULT NULL,
  `contract_image` VARCHAR(1000) NULL DEFAULT NULL,
  `contract_types_id` INT NOT NULL,
  `archieve` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`, `contract_types_id`),
  INDEX `fk_contracts_contract_types1_idx` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_contracts_contract_types1` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_EN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_EN` VARCHAR(100) NOT NULL,
  `part2_EN` VARCHAR(50) NULL,
  `inputType` LONGTEXT NOT NULL,
  `options` VARCHAR(250),
  `date` VARCHAR(10) NOT NULL,
  `explanation` VARCHAR(1000),
  `text_Area` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;
-- -----------------------------------------------------
-- Table `etafakna`.` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_FR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_FR` VARCHAR(100) NOT NULL,
  `part2_FR` VARCHAR(100) NULL,
  `inputType` LONGTEXT NULL,
  `options` VARCHAR(250),
  `date` VARCHAR(10)  NULL,
  `explanation` VARCHAR(1000),
  `text_Area` VARCHAR(10)  NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

 ALTER TABLE `etafakna`.`questions_FR` AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `etafakna`.` 
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_AR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content_AR` VARCHAR(100)  NULL,
  `part2_AR` VARCHAR(50) NULL,
  `inputType` LONGTEXT  NULL,
  `options` VARCHAR(250),
  `date` VARCHAR(10)  NULL,
  `explanation` VARCHAR(1000),
  `text_Area` VARCHAR(10)  NULL,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB CHARACTER SET = utf8 COLLATE = utf8_unicode_ci;

 ALTER TABLE `etafakna`.`questions_AR` AUTO_INCREMENT = 1;

-- -----------------------------------------------------
-- Table `etafakna`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(5000) NULL,
  `contracts_id` INT NOT NULL,
  `contracts_contract_types_id` INT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (
    `id`,
    `contracts_id`,
    `contracts_contract_types_id`,
    `questions_id`
  ),
  INDEX `fk_answers_questions2_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions2` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions_FR` (`id`)  ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`questions_has_contract_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_has_contract_types_EN` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `contract_types_id` INT NOT NULL,
  `order_question` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_has_contract_types_questions_EN` (`questions_id` ASC) VISIBLE,
  INDEX `fk_questions_has_contract_types_contract_types0` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_contract_types_contract_types0` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_questions_has_contract_types_questions_EN` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`questions_has_contract_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_has_contract_types_FR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `contract_types_id` INT NOT NULL,
  `order_question` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_has_contract_types_questions_FR` (`questions_id` ASC) VISIBLE,
  INDEX `fk_questions_has_contract_types_contract_types2` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_contract_types_contract_types2` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_questions_has_contract_types_questions_FR` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`questions_has_contract_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`questions_has_contract_types_AR` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `questions_id` INT NOT NULL,
  `contract_types_id` INT NOT NULL,
  `order_question` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_questions_has_contract_types_questions_AR` (`questions_id` ASC) VISIBLE,
  INDEX `fk_questions_has_contract_types_contract_types3` (`contract_types_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_has_contract_types_contract_types3` FOREIGN KEY (`contract_types_id`) REFERENCES `etafakna`.`contract_types` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_questions_has_contract_types_questions_AR` FOREIGN KEY (`questions_id`) REFERENCES `etafakna`.`questions` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(200) NOT NULL,
  `last_name` VARCHAR(200) NOT NULL,
  `username` VARCHAR(200) ,
  `email` VARCHAR(200) NOT NULL,
  `password` VARCHAR(200) NOT NULL,
  `address` VARCHAR(200) ,
  `phone` VARCHAR(200) NOT NULL,
  `role` VARCHAR(200) NOT NULL,
  `image` VARCHAR(200),
  `status` VARCHAR(200) NOT NULL,
  `created_at` DATE NULL DEFAULT NULL,
  `notification` VARCHAR(200) NULL DEFAULT NULL,
  `signatureUrl` VARCHAR(200) NULL DEFAULT NULL,
  `carteCinFront` VARCHAR(200) NULL DEFAULT NULL,
  `carteCinBack` VARCHAR(200) NULL DEFAULT NULL,
  `faceVideo` VARCHAR(200) NULL DEFAULT NULL,
  `scanSignature` VARCHAR(200) NULL DEFAULT NULL,
  `scanSignatureCheck` VARCHAR(200) NULL DEFAULT false,
  `formulaireCheck` VARCHAR(200) NULL DEFAULT false,
  `CINCheck` VARCHAR(200) NULL DEFAULT false,
  `videiSelfieCheck` VARCHAR(200) NULL DEFAULT false,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`users_has_contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`users_has_contracts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `contracts_id` INT NOT NULL,
  `receiver` INT NULL DEFAULT NULL,
  `receiver_email` VARCHAR(45) NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_contracts_contracts1_idx` (`contracts_id` ASC) VISIBLE,
  INDEX `fk_users_has_contracts_users1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_contracts_contracts1` FOREIGN KEY (`contracts_id`) REFERENCES `etafakna`.`contracts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_users_has_contracts_users1` FOREIGN KEY (`owner`) REFERENCES `etafakna`.`users` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `etafakna`.`users_has_notifications`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `etafakna`.`users_has_notifications` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `owner` INT NOT NULL,
  `contracts_id` INT NOT NULL,
  `receiver` INT NULL DEFAULT NULL,
  `date` VARCHAR(45) NULL DEFAULT NULL,
  `seen` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_has_notification_contracts1_idx` (`contracts_id` ASC) VISIBLE,
  INDEX `fk_users_has_notification_users1_idx` (`owner` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_notification_notification` FOREIGN KEY (`contracts_id`) REFERENCES `etafakna`.`contracts` (`id`) ON DELETE CASCADE,
  CONSTRAINT `fk_users_has_notification_users1` FOREIGN KEY (`owner`) REFERENCES `etafakna`.`users` (`id`) ON DELETE CASCADE
) ENGINE = InnoDB DEFAULT CHARACTER SET = utf8mb4 COLLATE = utf8mb4_0900_ai_ci;

SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;

-- insert questions 
INSERT INTO etafakna.questions_AR(content_AR,part2_AR,inputType,options,date,explanation,text_Area)
VALUES

-- Attestation de stage
(N'اسم و لقب  ',N' صاحب/ة الشركة',null,null,"false",null,"null"),
(N'عدد بطاقة التعريف الوطنية',N'صاحب/ة الشركة',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف ',N'صاحب/ة الشركة',null,null,"true",null,"null"),
(N'اسم الشركة ',NULL,null,null,"false",null,"null"),
(N'مقر الشركة',NULL,null,null,"false",null,"null"),
(N'اسم و لقب  ',N'المتربص/ة',null,null,"false",null,"null"),
(N'عدد بطاقة التعريف الوطنية',N'المتربص/ة',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف ',N'المتربص/ة',null,null,"true",null,"null"),
(N'اختصاص التربص ',null,null,null,"false",null,"null"),
(N'مدة التربص',N'بالأشهر',null,null,"false",null,"null"),
(N'بداية فترة التربص',null,null,null,"true",null,"null"),
(N'نهاية فترة التربص',null,null,null,"true",null,"null"),
(N'تاريخ الامضاء  ',null,null,null,"true",null,"null"),

-- CDD
(N'اسم الشركة المؤجرة',null,null,null,"false",null,"null"),
(N'المقر الاجتماعي للشركة',null,null,null,"false",null,"null"),
(N'اسم و لقب ',N'الممثل القانوني للشركة',null,null,"false",null,"null"),
(N'اسم و لقب ',N'الأجير/ة',null,null,"false",null,"null"),
(N'جنسية ',N'الأجير/ة',null,null,"false",null,"selector"),
(N'مكان ولادة',N'الأجير/ة',null,null,"false",null,"null"),
(N'رقم بـطـاقـة التعريف الـوطنيـة',N'الأجير/ة',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف',N'الأجير/ة',null,null,"true",null,"null"),

(N'عنوان ',N'الأجير/ة',null,null,"false",null,"null"),

(N'المنصب المشغور في العمل ',null,null,null,"false",null,"null"),
(N'مـدة العمل ',N'بالأشهر',null,null,"false",null,"null"),
(N'بداية من ',null,null,null,"true",null,"null"),
(N'الى غاية  ',null,null,null,"true",null,"null"),
(N'الأجـر الشهري ',null,null,null,"false",null,"null"),
(N'فترة التجربة المحددة  ',N'بالاشــهـر',null,null,"false",null,"null"),
(N'تاريخ امضاء العقد  ',null,null,null,"true",null,"null"),

-- CDI
(N'اسم الشركة المؤجرة',null,null,null,"false",null,"null"),
(N'المقر الاجتماعي للشركة',null,null,null,"false",null,"null"),
(N'اسم و لقب ',N'الممثل القانوني للشركة',null,null,"false",null,"null"),
(N'اسم و لقب ',N'الأجير/ة',null,null,"false",null,"null"),
(N'رقم بـطـاقـة التعريف الـوطنيـة',N'الأجير/ة',null,null,"false",null,"null"),
(N'عنوان ',N'الأجير/ة',null,null,"false",null,"null"),
(N'المنصب المشغور في العمل ',null,null,null,"false",null,"null"),
(N'الأجـر الشهري ',null,null,null,"false",null,"null"),
(N'مكان العمل',null,null,null,"false",null,"null"),
(N'تاريخ بداية تنفيذ العقد',null,null,null,"true",null,"null"),
(N'فترة التجربة المحددة  ',N'بالاشــهـر',null,null,"false",null,"null"),
(N'تاريخ امضاء العقد  ',null,null,null,"true",null,"null"),

-- loc dahabitation
(N'اسم و لقب ',N'المالك',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'المالك',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المالك',null,null,"true",null,"null"),
(N'اسم و لقب ',N'المتسوغ',null,null,"false",null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"true",null,"null"),
(N'عنوان  المحل الموضوع الكراء ',null,null,null,"false",null,"null"),
(N'عدد غرف المحل ',null,null,null,"false",null,"null"),
(N'مدة الكراء',N'بالاشــهـر',null,null,"false",null,"null"),
(N'بداية من',null,null,null,"true",null,"null"),
(N' إلى تاريخ ',null,null,null,"true",null,"null"),
(N' معين الكراء الشهري',null,null,null,"false",null,"null"),
(N' قيمة الضمان',null,null,null,"false",null,"null"),
(N' مكان الامضاء',null,null,null,"false",null,"null"),
(N'تاريخ الامضاء',null,null,null,"true",null,"null"),

-- loc commercial 
(N'اسم و لقب ',N'المالك',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'المالك',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المالك',null,null,"true",null,"null"),
(N'اسم و لقب ',N'المتسوغ',null,null,"false",null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"false",null,"null"),
(N'تاريخ صدور بطاقة التعريف الوطنية ',N'المتسوغ',null,null,"true",null,"null"),
(N'عنوان  المحل الموضوع الكراء ',null,null,null,"false",null,"null"),
(N'مساحة المحل ',N'بالمتر المربع ',null,null,"false",null,"null"),
(N'النشاط التجاري الذي سيتم تعاطيه في المحل',null,null,null,"false",null,"null"),
(N'مدة الكراء',N'بالاشــهـر',null,null,"false",null,"null"),
(N'بداية من',null,null,null,"true",null,"null"),
(N' إلى تاريخ ',null,null,null,"true",null,"null"),
(N' معين الكراء الشهري',null,null,null,"false",null,"null"),
(N' قيمة الضمان',null,null,null,"false",null,"null"),
(N' مكان الامضاء',null,null,null,"false",null,"null"),
(N'تاريخ الامضاء',null,null,null,"true",null,"null"),

-- loc dengagement 
(N'اسم و لقب ',N' القائم بالالتزام',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'المالك',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N' القائم بالالتزام',null,null,"true",null,"null"),
(N'عنوان',N' القائم بالالتزام',null,null,"false",null,"null"),
(N'موضوع الالتزام بالتفصيل',null,null,null,"false",null,null),
(N'تاريخ تعمير الاستمارة ',null,null,null,"true",null,"null"),

-- atte honneur 
(N'اسم و لقب ',N' القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N' القائم بالتصريح',null,null,"true",null,"null"),
(N' عنوان سكنى',N' القائم بالتصريح',null,null,"false",null,"null"),
(N' التصريح بالتفصيل',null,null,null,"false",null,null),
(N' تاريخ التصريح',null,null,null,"true",null,null),

-- atte domiciel 
(N'اسم و لقب ',N' القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'القائم/ة بالتصريح',null,null,"false",null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N' القائم بالتصريح',null,null,"true",null,"null"),
(N' اسم الشركة',null,null,null,"false",null,"null"),
(N' نوع الشركة',null,null,null,"false",null,"null"),
(N' رأسمال الشركة',null,null,null,"false",null,"null"),
(N' العنوان',null,null,null,"false",null,"null"),
(N' مقابل الاقامة ',null,null,null,"false",null,"null"),
(N' تاريخ تعمير الاستمارة  ',null,null,null,"true",null,"null"),

-- freelance normal person
(N'اسم و لقب ',N' المؤجر/ة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' للمؤجر/ة ',null,null,"false",null,"null"),
(N'اسم و لقب ',N' منفذ/ة العمل الحر',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' منفذ/ة العمل الحر ',null,null,"false",null,"null"),
(N' مجال العمل الحرّ',null,null,null,"false",null,"null"),
(N' تحديد العمل موضوع العقد بالتفصيل',null,null,null,"false",null,"null"),
(N'المدة التي سيمتد خلالها العمل الحر',N'بالاشــهـر',null,null,"false",null,"null"),
(N'المقابل  ',N'بالدينار التونسي',null,null,"false",null,"null"),
(N'تاريخ آخر أجل للخلاص ',null,null,null,"true",null,"null"),
(N' تاريخ إجراء الامضاء ',null,null,null,"true",null,"null"),

-- freelance company
(N' اسم الشركة ' ,N' المؤجر/ة',null,null,"false",null,"null"),
(N' اسم ولقب ' ,N'من سيمثل الشركة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'من سيمثل الشركة ',null,null,"false",null,"null"),
(N'اسم و لقب ',N' منفذ/ة العمل الحر',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' منفذ/ة العمل الحر ',null,null,"false",null,"null"),
(N' مجال العمل الحرّ',null,null,null,"false",null,"null"),
(N' تحديد العمل موضوع العقد بالتفصيل',null,null,null,"false",null,"null"),
(N'المدة التي سيمتد خلالها العمل الحر',N'بالاشــهـر',null,null,"false",null,"null"),
(N'المقابل  ',N'بالدينار التونسي',null,null,"false",null,"null"),
(N'تاريخ آخر أجل للخلاص ',null,null,null,"true",null,"null"),
(N' تاريخ إجراء الامضاء ',null,null,null,"true",null,"null"),

-- achat de voiture
(N'اسم و لقب ',N'بائع/ة السيارة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N'بائع/ة السيارة ',null,null,"false",null,"null"),
(N' مقر سكنى',N'بائع/ة السيارة ',null,null,"false",null,"null"),
(N'اسم و لقب ',N' مشتري/ة السيارة',null,null,"false",null,"null"),
(N' رقم بطاقة التعريف الوطنية',N' مشتري/ة السيارة ',null,null,"false",null,"null"),
(N' مقر سكنى',N' مشتري/ة السيارة ',null,null,"false",null,"null"),
(N' صانع السيارة ',null ,null,"marque","false",N'المصنع اي علامة السيارة كان تكون مرسيدس / بيجو …',"null"),
(N'نوع السيارة ',null ,null,"cartype","false",null,"null"),
(N'العدد الرتبي بالمصنع ',null ,null,null,"false",null,"null"),
(N'القوة المقدرة ',N'بالحصان' ,null,null,"false",null,"null"),
(N'وقود السيارة  ',null ,null,"energy","false",null,"null"),
(N'تاريخ أول إذن بالجولان  ',null ,null,null,"true",null,"null"),
(N'رقم التسجيل للسيارة  ',null ,null,null,"false",null,"null"),
(N'ثمن بيع السيارة  ',N'بالدينار التونسي' ,null,null,"false",null,"null"),
(N'تاريخ تحرير العقد  ',null ,null,null,"true",null,"null"),

-- vente 
(N'اسم ولقب ',N'البائع/ة' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'البائع/ة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'البائع/ة' ,null,null,null,null,"null"),
(N'اسم ولقب ',N'المشتري/ة' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'المشتري/ة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'المشتري/ة' ,null,null,null,null,"null"),
(N'موضوع عقد البيع و وصفه ',null ,null,null,null,null,"null"),
(N'ثمن البيع  ',N'بالدينار التونسي' ,null,null,null,null,"null"),
(N'تاريخ تحرير العقد  ',N'بالدينار التونسي' ,null,null,"true",null,"null"),

-- demande officiel 
(N'موضوع المطلب ',null ,null,null,null,null,"null"),
(N'اسم ولقب ',N'القائم/ة بالمطلب' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف الوطنية ',N'القائم/ة بالمطلب' ,null,null,null,null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'القائم/ة بالمطلب',null,null,"true",null,"null"),
(N' عنوان سكنى',N'القائم/ة بالمطلب',null,null,"false",null,"null"),
(N' صفة القائم بالمطلب',null,null,null,"false",N'طالب اذا كان المطلب موجه الى ادارة الكلية او موظف في الشركة اذا المطلب موجه للشركة الموظفة او ولي امر التلميذ/ة , بالنسبة للمدرسة او المعهد…',"null"),
(N'الهيكل أو صفة الشخص المسؤول ',N'المطلوب منه',null,null,"false",N' تحديد الطرف الموجه له المطلب: مثلا عميدة كلية العلوم بتونس, او المدير التنفيذي للبنك , او وزارة التربية والتعليم…',"null"),
(N' موضوع المطلب بالتفصيل',null,null,null,"false",null,"null"),
(N' تاريخ  تحرير المطلب ',null,null,null,"true",null,"null"),

-- procuration 
(N'اسم ولقب ',N'الموكل' ,null,null,null,N'الشخص اللي بش يعطيك التوكيل وبش تاخو بلاصتو',"null"),
(N'رقم بطاقة التعريف  ',N'الموكل' ,null,null,null,null,"null"),
(N'صفة الموكل',null ,null,null,null,null,"null"),
(N'اسم ولقب ',N'الوكيل' ,null,null,null,N'الشخص اللي بش يقوم بالتوكيل يعني اللي بش يقضي هو القضية في بلاصت العبد الآخر',"null"),
(N'رقم بطاقة تعريف',N'الوكيل ' ,null,null,null,null,"null"),
(N'الغرض من التوكيل',null ,null,null,null,N'مثلا لتمثيلي امام البلدية او لتمثيلي امام المجلس كذا كذا او امام الوزارة كذا كذا…',"null"),

-- CIVP
(N'اسم المؤسسة',null ,null,null,null,null,"null"),
(N'قطاع نشاط المؤسسة',null ,null,null,null,null,"null"),
(N' البريد الألكتروني للمؤسسة',null ,null,null,null,null,"null"),
(N' المقر الإجتماعي للمؤسسة',null ,null,null,null,null,"null"),
(N' المعرف الجبائي للمؤسسة',null ,null,null,null,null,"null"),
(N' رقم الانخراط بالصندوق الوطني للضمان الجتماعي للمؤسسة',null ,null,null,null,null,"null"),
(N'اسم ولقب',N'رئيس المؤسسة' ,null,null,null,null,"null"),
(N'اسم ولقب',N'الممثل القانوني للمؤسسة' ,null,null,null,null,"null"),
(N'اسم ولقب',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'مكان ولادة ',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'تاريخ ولادة ',N'المنتفع/ة' ,null,null,"true",null,"null"),
(N'رقم بطاقة التعريف الوطنية',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'عنوان ',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'البريد الالكتروني',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'المستوى التعليمي ',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'الاختصاص',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'الشهادة التي تحصل عليها',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'تاريخ الحصول على الشهادة',N'المنتفع/ة' ,null,null,"true",null,"null"),
(N'الحساب الجاري',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'فرع البنك أو مكتب البريد',null ,null,null,null,null,"null"),
(N'المنصب المشغور في العمل',N'المنتفع/ة' ,null,null,null,null,"null"),
(N'اسم ولقب',N'المؤطر/ة للمنتفع/ة' ,null,null,null,null,"null"),
(N'صفة المؤطر/ة بالمؤسسة',null ,null,null,null,null,"null"),
(N'المقر الذي يجري فيه العمل',null ,null,null,null,null,"null"),
(N'تاريخ بداية عقد العمل',null ,null,null,"true",null,"null"),
(N'تاريخ نهاية عقد العمل ',null ,null,null,"true",null,"null"),
(N'المنحة الشهرية المتحصل عليها من قبل الوكالة الوطنية للتشغيل والعمل المستقل',N'بالدينار' ,null,null,null,null,"null"),
(N'المنحة الشهرية المتحصل عليها مباشرة من المشغل',N'بالدينار' ,null,null,null,null,"null"),
(N'تاريخ تحرير العقد',null ,null,null,"true",null,"null"),

-- NDA
(N'اسم ولقب',N'صاحب المعلومة',null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'صاحب المعلومة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'صاحب المعلومة' ,null,null,null,null,"null"),
(N'اسم المؤسسة المعنية بالمعلومات',null ,null,null,null,null,"null"),
(N'اسم ولقب',N'متلقي/ة المعلومة',null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'متلقي/ة المعلومة' ,null,null,null,null,"null"),
(N'مقر سكنى ',N'متلقي/ة المعلومة' ,null,null,null,null,"null"),
(N'تحديد مدة الاتفاقية ',N' بالسنوات' ,null,null,null,null,"null"),

-- Pret_entre_parti
(N'اسم ولقب ',N'المقرض' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'المقرض' ,null,null,null,null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المقرض',null,null,"true",null,"null"),
(N'اسم ولقب ',N'المقترض' ,null,null,null,null,"null"),
(N'رقم بطاقة التعريف',N'المقترض' ,null,null,null,null,"null"),
(N' تاريخ صدور بطاقة التعريف الوطنية',N'المقترض',null,null,"true",null,"null"),
(N'مبلغ القرض ',N'بالدينار التونسي' ,null,null,null,null,"null"),
(N'تاريخ آخر أجل لتسديد ال‍دين',null,null,null,"true",null,"null"),
(N' مكان العقد',null,null,null,"false",null,"null"),
(N'تاريخ العقد',null,null,null,"true",null,"null");


INSERT INTO etafakna.questions_FR(content_FR,part2_FR,inputType,options,date,explanation,text_Area)
VALUES

-- DEMANDE OFFICIEL
("A l'attention",N'Civilité du destinataire',null,"civilite","false",null,"nukk"),
(N'Nom et prénom',N'Du destinataire',null,null,"false",null,"nukk"),
(N'Quel est l’objet de votre demande',null,null,null,"false",null,"nukk"),
(N'Veuillez préciser votre demande',null,null,null,"false",null,"textArea"),
(N'Fait à',N'Veuillez préciser votre gouvernorat',null,null,"false",null,null),
("Date de la demande",null,null,null,"true",null,null),
(N'Civilité',"Du demandeur",null,"civilite","false",null,null),
(N'Votre nom et prénom',"Du demandeur",null,null,"false",null,null),

-- CDD
(N'Nom de la société',null,null,null,null,"prrrrrrr",null),
(N'Activité de la société',null,null,null,null,null,null), 
(N'Adresse de la société',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Civilité',N'Du gérant',"n","civilite","n",null,null),
(N'Nom et prénom',N'Du gérant(e)',"n","n","n",null,null),
(N'Civilité',N'De l’employé',"n","civilite","n",null,null),
(N'Nom et prénom',N'De l’employé',"n","n","n",null,null),
("Statut",N'De l’employé',"n","status","n",null,null),
("Lieu de naissance",null,"n","n","n",null,null),
("Date de naissance",null,"n","n","true",null,null),
(N'Numéro de la carte d identité',null,"n","n","n",null,null),
(N'CIN délivrée le',null,"n","n","true",null,null),
(N'Adresse',N'De l’employé',N'Rue, Gouvernorat, Code postal',"n","n",null,null),
("Fonction",N'De l’employé',"n",null,null,null,null),
(N'Début du contrat',null,null,null,"true",null,null),
("Fin du contract",null,null,null,"true",null,null),
("Salaire mensuel","En dinars",null,"words",null,null,null),
(N'Fait à',N'Veuillez préciser votre gouvernorat',null,null,"false",null,null),
("Date du contract",null,null,null,"true",null,null),

-- CONTRACT DE LOCATION A USAGE Bureau
(N'Civilité',N'Du propriétaire',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du propriétaire',null,null,"false",null,null),
(N'N° la carte CIN',N'Du propriétaire',null,null,"false",null,null),
(N'CIN délivrée le',N'Du propriétaire',null,null,"true",null,null),
(N'Adresse du propriétaire',"Rue, gouvernorat et code postal",null,null,"false",null,null),
(N'Nom de la société',"Le locataire",null,null,"false",null,null),
(N'Forme juridique',"Le locataire",null,"form","false",null,null),
(N'Capital de la société',"En dinars",null,null,"false",null,null),
(N'N° du registre de commerce',null,null,null,"false",null,null),
(N'Adresse du siège de la société',N'Rue, Gourvenorat, Code postal',null,null,"false",null,null),
(N'Civilité',N'Du représentant légal de la société',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du représentant légal de la société',null,null,"false",null,null),
(N'Fonction',N'Du représentant légal de la société',null,null,"false",null,null),
(N'N° la carte CIN',N'Du représentant légal de la société',null,null,"false",null,null),
(N'CIN délivrée le',N'Du représentant légal de la société',null,null,"true",null,null),
(N'Location à usage',null,null,"CommercialCase",null,null,null),
(N'bref descriptif du local et meubles inclus',null,null,null,null,null,null),
(N'Adresse du local à louer',"Rue, gouvernorat et code postal",null,null,"false",null,null),
(N'Durée de la location',N'En mois',null,null,null,null,null),
(N'Date du début de la location',null,null,null,"true",null,null),
(N'Date de la fin de la location',null,null,null,"true",null,null),
(N'Montant mensuel de la location',"En dinars",null,null,null,null,null),
(N'Montant du cautionnement ',"En dinars",null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat ',null,null,null,"true",null,null),

-- CONTRACT DE LOCATION  à usage d'habitation
(N'Civilité',N'Du propriétaire',null,"civilite",null,null,null),
(N'Entrez le nom et prénom',N'Du propriétaire',null,null,null,null,null),
(N'Adresse',N'Du propriétaire: Rue,gouvernorat et code postal',null,null,null,null,null),
(N'N° de la carte CIN',N'Du propriétaire',null,null,null,null,null),
(N'CIN délivrée le',N'Du propriétaire',null,null,"true",null,null),
(N'Civilité',"Du locataire",null,"civilite",null,null,null),
(N'Entrez le nom et prénom',"Du locataire",null,null,null,null,null),
(N'N° de la carte CIN',"Du locataire",null,null,null,null,null),
(N'CIN délivrée le',"Du locataire","true",null,"true",null,null),
(N'Décrivez le type de propriété',null,null,"typeproprite",null,null,null),
(N'Composée de',N'La propriété: Salon ',null,null,null,null,null),
(N'Composée de',N'La propriété: Chambre  ',null,null,null,null,null),
(N'Composée de',N'La propriété: Cuisine et salle à manger  ',null,null,null,null,null),
(N'Composée de',N'La propriété: Salle de bain/d’eau ',null,null,null,null,null),
(N'Adresse de la propriété',N'Rue,gouvernorat et code postal',null,null,null,null,null),
(N'Durée de la location',N'En mois',null,null,null,null,null),
(N'Date de début de la location',null,"true",null,"true",null,null),
(N'Date de fin de la location',null,"true",null,"true",null,null),
(N'Montant de la location',"En dinars",null,null,null,null,null),
(N'Montant du cautionnement',"En dinars",null,null,null,null,null),
(N'Frais du syndic mensuel ',"En dinars",null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville',null,null,null,null,null),
(N'Date du contrat',null,"true",null,"true",null,null),

-- CONTRACT DENGAGEMENT
(N'Civilité',N'De l’engagé(e)',null,"civilite","n",null,null),
(N'Nom et prénom',N'De l’engagé(e)',null,null,"false",null,null),
(N'Numéro de CIN',null,null,null,null,null,null),
(N'CIN délivrée le',null,null,null,"true",null,null),
(N'Indiquer la fonction',N'De l’engagé(e)',null,null,null,null,null),
(N'Nom de ma société',null,null,null,null,null,null),
(N'Identifiant unique',null,null,null,null,null,null),
(N'Je m`engage',null,null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Fait le',null,null,null,"true",null,null),

-- Contrat de Domiciliation
(N'Civilité',N'Du représentant(e) légal',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du représentant(e) légal',null,null,null,null,null),
(N'Numéro de carte CIN',null,null,null,null,null,null),
(N'CIN délivrée le',null,null,null,"true",null,null),
(N'Nom de la société',N'Nom de la société',null,null,null,null,null),
(N'Forme juridique',null,null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,null,null,null,null),
(N'Adress du siège',N'Rue, Gouvernorat, Code postal ',null,null,null,null,null),
(N'A titre',null,null,"titre",null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Fait le',null,null,null,"true",null,null),

-- Contrat de attestation de stage
(N'Civilité',"Employeur","civilite","civilite",null,null,null),
(N'Nom et prénom',"Employeur",null,null,null,null,null),
(N'Indiquer le fonction dans l’entreprise',"Employeur",null,null,null,null,null),
(N'Civilité',"Stagiare",null,"civilite",null,null,null),
(N'Nom et prénom',"Stagiare",null,null,null,null,null),
(N'Adresse du Stagiare',N'Rue, gouvernorat et code postal',null,null,null,null,null),
(N'Nom de l’entreprise',null,null,null,null,null,null),
(N'Date du début de stage',null,"true",null,"true",null,null),
(N'Date de fin du stage',null,"true",null,"true",null,null),
(N'Indiquer le poste dans l’entreprise',"Stagiaire",null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Fait le',null,null,null,"true",null,null),

-- CIVP 
(N'Nom de la société',null,null,null,null,null,null),
(N'Activité de la société ',null,null,null,null,null,null),
(N'Adresse de la société ',N'Rue',null,null,null,null,null),
(N'Adresse de la société ',N'Gouvernorat',null,null,null,null,null),
(N'Adresse de la société ',N'Pays',null,null,null,null,null),
(N'Adresse de la société ',N'Code Postal',null,null,null,null,null),
(N'Adresse électronique',null,null,null,null,null,null),
(N'Numéro de téléphone',null,null,null,null,null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Numéro d’affiliation CNSS',null,null,null,null,null,null),
(N'Civilité ',N'Du gérant(e) ',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du gérant(e)',null,null,null,null,null),
(N'Civilité ',N'Du représentant',null,"civilite",null,null,null),
(N'Nom et prénom',N'Du remplaçant',null,null,null,null,null),
(N'En qualité de :',N'Du remplaçant',null,null,null,null,null),
(N'Numéro de téléphone ',N'Du représentant',null,null,null,null,null),
(N'Civilité ',N'Du bénéficiaire ',null,"civilite",null,null,null),
(N'Nom et prénom',N'Bénéficaire du CIVP',null,null,null,null,null),
(N'Date de naissance',N'Bénéficaire du CIVP',null,null,"true",null,null),
(N'Lieu de naissance',N'Bénéficaire du CIVP',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Rue',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Gouvernorat',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Pays',null,null,null,null,null),
(N'Adresse du bénéficiare',N'Code Postal',null,null,null,null,null),
(N'Adresse électronique',N'Bénéficiare',null,null,null,null,null),
(N'Niveau scolaire ',N'Bénéficiare',null,null,null,null,null),
(N'Diplôme & specialité',N'Bénéficiare',null,null,null,null,null),
(N'Date d’obtention du diplôme',null,null,null,"true",null,null),
(N'N°du compte courant',null,null,null,null,null,null),
(N'Agence bancaire ou postale',null,null,null,null,null,null),
(N'Poste occupé',N'bénéficiare',null,null,null,null,null),
(N'Durée du contrat ',"Du",null,null,"true",null,null),
(N'Durée du contrat ',"Au",null,null,"true",null,null),
(N'Montant de la subvention CIVP',N'En dinars',null,null,null,null,null),
(N'Salaire mensuel',N'En dinars',null,null,null,null,null),
(N'Fait à',N'Précisez le nom de la ville',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- Procuration 
(N'Civilité ',N'Du Mandant',null,"civilite",null,N'C’est la personne qui donne la procuration',null),
(N'Nom et Prénom ',N'Du Mandant',null,null,null,N'C’est la personne qui donne la procuration',null),
(N'Numéro de la carte CIN',N'Du Mandant',null,null,null,N'C’est la personne qui donne la procuration',null),
(N'Date de délivrance de la carte CIN',N'Du Mandant',null,null,"true",N'C’est la personne qui donne la procuration',null),
(N'Adresse du mandant',N'Rue, gouvernorat et code postal',null,null,null,null,null),
(N'Civilité ',N'Du mandataire ',null,"civilite",null,N'C’est la personne qui donne la procuration',null),
(N'Nom et Prénom ',N'Du mandataire ',null,null,null,N'C’est la personne qui donne la procuration',null),
(N'Numéro de la carte CIN',N'Du mandataire',null,null,null,N'C’est la personne qui donne la procuration',null),
(N'Date de délivrance de la carte CIN',N'Du mandataire',null,null,"true",N'C’est la personne qui donne la procuration',null),
(N'Adresse Du mandataire',N'Rue, gouvernorat et code postal',null,null,null,null,null),
(N'L`object de la procuration',null,null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- freelance
(N'Civilité',N'Du freelanceur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du freelanceur',null,null,null,null,null),
(N'N° de la CIN',N'Du freelanceur',null,null,null,null,null),
(N'CIN délivrée le',N'Du freelanceur',null,null,"true",null,null),
(N'Précisez le domaine de compétence',N'Du freelanceur',null,null,null,null,null),
(N'Civilité',N'Du client',null,N'civilite',null,null,null),
(N'Nom et prénom',N'Du client',null,null,null,null,null),
(N'Fonction',N'Du client',null,null,null,N'exemple: gérant(e) / responsable departement commerciale de la société XYZ…',null),
(N'Nom de la société ',N'Du client',null,null,null,null,null),
(N'N° du registre de commerce',N'Du client',null,null,null,null,null),
(N'Adresse du siége social',N'Rue, gouvernorat et code postal',null,null,null,null,null),
(N'Précisez la mission du freelanceur',null,null,null,null,null,null),
(N'Date du début de la mission',null,null,null,"true",null,null),
(N'Date de la fin de la mission',null,null,null,"true",null,null),
(N'Montant de la rémunération',N'En dinars',null,null,null,null,null),
(N'Date limite du paiement',null,null,null,"true",null,null),
(N'Fait à ',N'Précisez le nom de la ville',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- Contrat d’achat et de vente
(N'Civilité ',N'Du vendeur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du vendeur',null,null,null,null,null),
(N'N° de la CIN',N'Du vendeur',null,null,null,null,null),
(N'CIN délivrée le',N'Du vendeur',null,null,"true",null,null),
(N'Civilité ',N'De l’acheteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'De l’acheteur',null,null,null,null,null),
(N'N° de la CIN',N'De l’acheteur',null,null,null,null,null),
(N'CIN délivrée le',N'De l’acheteur',null,null,"true",null,null),
(N'Veuillez précisez le produit/objet acheté',null,null,null,null,null,null),
(N'Montant à payer',N'En dinars',null,null,null,null,null),
(N'Mentionnez la date du paiement ',null,null,null,"true",null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- Contrat de prêt d’argent entre particulier
(N'Civilité ',N'Du prêteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du prêteur',null,null,null,null,null),
(N'N° de la CIN',N'Du prêteur',null,null,null,null,null),
(N'Adresse du Prêteur',N'Rue, Gouvernorat et code postal',null,null,null,null,null),
(N'Civilité ',N'De l’emprunteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'De l’emprunteur',null,null,null,null,null),
(N'N° de la CIN',N'De l’emprunteur',null,null,null,null,null),
(N'Adresse du l’emprunteur',N'Rue, Gouvernorat et code postal',null,null,null,null,null),
(N'Veuillez écrire le montant du Prêt',N'En dinars',null,null,null,null,null),
(N'Date du versement du prêt',null,null,null,"true",null,null),
(N'Date du paiement du prêt',null,null,null,"true",null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- vente voiture
(N'Civilité ',N'Le vendeur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Le vendeur',null,null,null,null,null),
(N'N° de la CIN',N'Le vendeur',null,null,null,null,null),
(N'CIN délivrée le',N'Le vendeur',null,null,"true",null,null),
(N'Civilité ',N'L’acheteur',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'L’acheteur',null,null,null,null,null),
(N'N° de la CIN',N'L’acheteur',null,null,null,null,null),
(N'CIN délivrée le',N'L’acheteur',null,null,"true",null,null),
(N'Quel est le N° Immatriculation ',N'Exp :197 TN 161',null,null,null,null,null),
(N'Précisez la date de la 1ère mise en circulation',N'Du Véhicule à vendre',null,null,"true",null,null),
(N'Précisez le genre',N'Ex: WA51BA',null,null,null,null,null),
(N'Précisez le marque ',N'Ex: Bmw, Audi, Fiat.. ',null,"marque",null,null,null),
(N'Précisez le type',N'Ex: Berline, coupé..',null,"cartype",null,null,null),
(N'Veuillez écrire le numéro de serie du vehicule',null,null,null,null,N' Le type et le numéro d’ordre dans la série du type doivent être constitué de 17 caractères Ex: wvw2223c1ab504347',null),
(N'Energie',null,null,"energy",null,null,null),
(N'Puissance',N'Par chevaux',null,null,null,null,null),
(N'Prix de vente de la voiture',N'En dinars',null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- NDA societe
(N'Nom de la société protectrice',null,null,null,null,null,null),
(N'Forme juridique ',null,null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,"number",null,null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Adresse du siége social',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité ',N'Du représentant légal',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du représentant légal',null,null,null,null,null),
(N'Fonction ',N'Du représentant légal',null,null,null,null,null),
(N'N° de la carte CIN',N'Du représentant légal',null,"number",null,null,null),
(N'Civilité ',N'De la personne engagée à la confidentialité ',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'De la personne engagée à la confidentialité ',null,null,null,null,null),
(N'N° la carte CIN',N'De la personne engagée à la confidentialité ',null,"number",null,null,null),
(N'Carte CIN délivrée le',N'De la personne engagée à la confidentialité ',null,null,"true",null,null),
(N'Veuillez définir la durée de l’accord de confidentialité',N'En mois',null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- NDA Paticulier
(N'Civilité ',N'De la partie protectrice',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'De la partie protectrice',null,null,null,null,null),
(N'N° de la carte CIN',N'De la partie protectrice',null,"number",null,null,null),
(N'Carte CIN délivrée le',N'De la partie protectrice',null,null,"true",null,null),
(N'Nom de la société',N'Engagée à la confidentialité',null,null,null,null,null),
(N'Forme juridique ',N'De la sociéte',null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,"number",null,null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Adresse du siége social',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité ',N'Du représentant légal',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du représentant légal',null,null,null,null,null),
(N'Fonction ',N'Du représentant légal',null,null,null,null,null),
(N'N° la carte CIN',N'Du représentant légal',null,"number",null,null,null),
(N'Veuillez définir la durée de l’accord de confidentialité',N'En mois',null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- atte travail 
(N'Civilité ',N'Du gérant',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du gérant',null,null,null,null,null),
(N'Nom de l’entreprise ',null,null,null,null,null,null),
(N'Civilité ',N'De l’employé(e)',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'De l’employé(e)',null,null,null,null,null),
(N'N° la carte CIN',N'De l’employé(e)',null,"number",null,null,null),
(N'Fonction ',N'De l’employé(e)',null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville',null,null,null,null,null),
(N'Date de l’attestation',null,null,null,"true",null,null),

-- commision 
(N'Civilité ',N'Du commettant ',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du commettant',null,null,null,null,null),
(N'N° la carte CIN',N'Du commettant ',null,"number",null,null,null),
(N'Carte CIN délivrée le',N'Du commettant',null,null,"true",null,null),
(N'Civilité ',N'Du commissionnaire ',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du commissionnaire ',null,null,null,null,null),
(N'N° la carte CIN',N'Du commissionnaire ',null,"number",null,null,null),
(N'Carte CIN délivrée le',N'Du commissionnaire',null,null,"true",null,null),
(N'Montant de la commission ',N'En dinars',null,null,null,null,null),
(N' Précisez l’activité relative à la commission ',null,null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

--  atte Honneur
(N'Civilité ',N'Du déclarant',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du déclarant',null,null,null,null,null),
(N'N° la carte CIN',N'Du déclarant',null,"number",null,null,null),
(N'Adresse',N'Du déclarant',N'Rue, Gouvernorat, Code postal',"n","n",null,null),
(N'J’atteste sur l’honneur que: ',null,N'Rue, Gouvernorat, Code postal',"n","n",null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date de l’attestation',null,null,null,"true",null,null),

--  atte CDI
(N'Nom de la société',null,null,null,null,null,null),
(N'Forme juridique ',null,null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,null,"false",null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Adress de la société',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité',N'Du gérant',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du gérant',null,null,null,null,null),
(N'Fonction ',N'Du gérant',null,null,null,null,null),
(N'N° la carte CIN',N'Du gérant',null,"number",null,null,null),
(N'Carte CIN délivrée le',N'Du gérant',null,null,"true",null,null),
(N'Civilité',N'De salairié(e)',"n","civilite","n",null,null),
(N'Nom et prénom',N'De salairié(e)',"n","n","n",null,null),
(N'N° la carte CIN',N'De salairié(e)',null,"number",null,null,null),
(N'Carte CIN délivrée le',N'De salairié(e)',null,null,"true",null,null),
(N'Adress de salairié(e)',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Fonction de salairié(e)',null,null,null,null,null,null),
(N'Date de début de contrat',null,null,null,"true",null,null),
(N'Nombre de mois d`éssai',null,null,"number",null,null,null),
(N'Début de la periode d`éssai',null,null,null,"true",null,null),
(N'Fin de la periode d`éssai',null,null,null,"true",null,null),
(N'Nombre d`heures de travail par semaine',null,null,"number",null,null,null),
(N'Salaire mensuel',N'En dinars',null,"number",null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date de contrat',null,null,null,"true",null,null),

-- location de voiture
(N'Civilité ',N'Du propriétaire',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Du propriétaire',null,null,null,null,null),
(N'N° de la CIN',N'Du propriétaire',null,null,null,null,null),
(N'CIN délivrée le',N'Du propriétaire',null,null,"true",null,null),
(N'Civilité ',N'Le locataire',null,"civilite",null,null,null),
(N'Nom et prénom  ',N'Le locataire',null,null,null,null,null),
(N'N° de la CIN',N'Le locataire',null,null,null,null,null),
(N'CIN délivrée le',N'Le locataire',null,null,"true",null,null),
(N'Quel est le N° Immatriculation ',N'Exp :197 TN 161',null,null,null,null,null),
(N'Précisez la date de la 1ère mise en circulation',N'Du Véhicule à vendre',null,null,"true",null,null),
(N'Précisez le genre',N'Ex: WA51BA',null,null,null,null,null),
(N'Précisez le marque ',N'Ex: Bmw, Audi, Fiat.. ',null,"marque",null,null,null),
(N'Précisez le type',N'Ex: Berline, coupé..',null,"cartype",null,null,null),
(N'Veuillez écrire le numéro de serie du vehicule',null,null,null,null,N' Le type et le numéro d’ordre dans la série du type doivent être constitué de 17 caractères Ex: wvw2223c1ab504347',null),
(N'Energie',null,null,"energy",null,null,null),
(N'Puissance',N'Par chevaux',null,null,null,null,null),
(N'Durée de la location',N'En jours',null,null,null,null,null),
(N'Date du début de la location',null,null,null,"true",null,null),
(N'Date de la fin de la location',null,null,null,"true",null,null),
(N'Frais de location en dinars',N'Par jours',null,null,null,null,null),
(N'Somme totale de la location',N'En dinars',null,null,null,null,null),
(N'Fait à ',N'Précisez le nom de la ville ou le contrat est signé',null,null,null,null,null),
(N'Date de contrat',null,null,null,"true",null,null),

-- prestation de service
(N'Nom de la société',N'Société bénéficiaire',null,null,null,null,null),
(N'Forme juridique ',null,null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,null,"false",null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Adresse de la société',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité ',N'Du représentant légal',null,"civilite",null,null,null),
(N'Nom et Prénom ',N'Du représentant légal',null,null,null,null,null),
(N'Nom de la société',N'Scoiété prestataire',null,null,null,null,null),
(N'Forme juridique ',null,null,"form",null,null,null),
(N'Capital de la société',"En dinars",null,null,"false",null,null),
(N'N° du registre de commerce',null,null,null,null,null,null),
(N'Adresse de la société',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité ',N'Du représentant légal',null,"civilite",null,null,null),
(N'Nom et Prénom ',null,null,null,null,null,null),
(N'Objet de la prestation',null,null,null,null,null,null),
(N'Prix de la prestation',N'En dinars',null,null,null,null,null),
(N'Durée du contrat',N'En mois',null,null,null,null,null),
(N'Date du début de la mission',null,null,null,"true",null,null),
(N'Date de la fin de la mission',null,null,null,"true",null,null),
(N'Fait à ',N'Précisez le nom de la ville',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null),

-- partenariat
(N'Nom de la société',N'Bénéficiaire',null,null,null,null,null),
(N'Adresse de la société',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité du représentant ',N'Bénéficiaire',null,"civilite",null,null,null),
(N'Nom et Prénom ',null,null,null,null,null,null),
(N'Nom de la société',N'Partenaire',null,null,null,null,null),
(N'Adresse de la société',N'Rue, Gouvernorat, Code postal',null,null,null,null,null),
(N'Civilité de représentant',N'Partenaire',null,"civilite",null,null,null),
(N'Nom et Prénom ',null,null,null,null,null,null),
/*2>9*/(N'Activité de la société',N'Bénéficiaire',null,null,null,null,null),
(N'Quel est le nom du projet de partenariat ?',null,null,null,null,null,null),
/*7>6*/(N'Activité de la société',N'Partenaire',null,null,null,null,null),
(N'Valeur de la contribution ',N'En dinars',null,null,null,null,null),
(N'Partenariat sous forme de',null,null,"formePartenariat",null,null,null),
(N'Date du délai d’exécution du partenariat',null,null,null,"true",null,null),
(N'Déterminez la contrepartie qui sera assurer par le bénéficiaire',null,null,null,null,N'Ex : Affichage du logo sur les panneaux publicitaires, mention de la marque…etc',null),
(N'Fait à ',N'Précisez le nom de la ville',null,null,null,null,null),
(N'Date du contrat',null,null,null,"true",null,null);





-- insert question-has-contracttype 
INSERT INTO etafakna.questions_has_contract_types_EN(questions_id, contract_types_id, order_question)
VALUES

   (1, 34, 1),
   (2, 34, 2),
   (3, 34, 3),
   (4, 34, 4),
   (5, 34, 1),
   (6, 19, 1);
 -- insert question-has-contracttype 


INSERT INTO etafakna.questions_has_contract_types_AR(questions_id, contract_types_id, order_question)
VALUES

-- attestation de stage
   (1,  3, 1),
   (2,  3, 2),
   (3,  3, 3),
   (4,  3, 4),
   (5,  3, 5),
   (6,  3, 6),
   (7,  3, 7),
   (8,  3, 8),
   (9,  3, 9),
   (10, 3, 10),
   (11, 3, 11),
   (12, 3, 12),
   (13, 3, 13),

  -- CDD
   (14, 18,1),
   (15, 18, 2),
   (16, 18, 3),
   (17, 18, 4),
   (19, 18, 6),
   (20, 18, 7),
   (21, 18, 8),
   (22, 18, 9),
   (23, 18, 10),
   (24, 18, 11),
   (25, 18, 12),
   (26, 18, 13),
   (27, 18, 14),
   (28, 18, 15),
   (29, 18, 16),

-- CDI
   (30, 17,1),
   (31, 17, 2),
   (32, 17, 3),
   (33, 17, 4),
   (34, 17, 5),
   (35, 17, 6),
   (36, 17, 7),
   (37, 17, 8),
   (38, 17, 9),
   (39, 17, 10),
   (40, 17, 11),
   (41, 17, 12),

-- LOC dahabitation
   (42, 21, 1),
   (43, 21, 2),
   (44, 21, 3),
   (45, 21, 4),
   (46, 21, 5),
   (47, 21, 6),
   (48, 21, 7),
   (49, 21, 8),
   (50, 21, 9),
   (51, 21, 10),
   (52, 21, 11),
   (53, 21, 12),
   (54, 21, 13),
   (55, 21, 14),
   (56, 21, 15),

-- LOC commercial
   (57, 20,1),
   (58, 20, 2),
   (59, 20, 3),
   (60, 20, 4),
   (61, 20, 5),
   (62, 20, 6),
   (63, 20, 7),
   (64, 20, 8),
   (65, 20, 9),
   (66, 20, 10),
   (67, 20, 11),
   (68, 20, 12),
   (69, 20, 13),
   (70, 20, 14),
   (71, 20, 15),
   (72, 20, 16),

-- contract dengagement
   (73, 8,1),
   (74, 8, 2),
   (75, 8, 3),
   (76, 8, 4),
   (77, 8, 5),
   (78, 8, 6),

-- attes honneur
   (79, 11,1),
   (80, 11, 2),
   (81, 11, 3),
   (82, 11, 4),
   (83, 11, 5),
   (84, 11, 6),

-- con domiciel
   (85, 12,1),
   (86, 12, 2),
   (87, 12, 3),
   (88, 12, 4),
   (89, 12, 5),
   (90, 12, 6),
   (91, 12, 7),
   (92, 12, 8),
   (93, 12, 9),

-- freelance normal person
   (94,  26,1),
   (95,  26, 2),
   (96,  26, 3),
   (97,  26, 4),
   (98,  26, 5),
   (99,  26, 6),
   (100, 26, 7),
   (101, 26, 8),
   (102, 26, 9),
   (103, 26, 10),

 -- freelance company
   (104, 27,1),
   (105, 27, 2),
   (106, 27, 3),
   (107, 27, 4),
   (108, 27, 5),
   (109, 27, 6),
   (110, 27, 7),
   (111, 27, 8),
   (112, 27, 9),
   (113, 27, 10),
   (114, 27, 11),

   -- achat de voiture
   (115, 22,1),
   (116, 22,2),
   (117, 22,3),
   (118, 22,4),
   (119, 22,5),
   (120, 22,6),
   (121, 22,7),
   (122, 22,8),
   (123, 22,9),
   (124, 22,10),
   (125, 22,11),
   (126, 22,12),
   (127, 22,13),
   (128, 22,14),
   (129, 22,15),

-- vente sample 
   (130,7,1),
   (131,7,2),
   (132,7,3),
   (133,7,4),
   (134,7,5),
   (135,7,6),
   (136,7,7),
   (137,7,8),
   (138,7,9),

-- demande off

   (139, 14,1),
   (140, 14,2),
   (141, 14,3),
   (142, 14,4),
   (143, 14,5),
   (144, 14,6),
   (145, 14,7),
   (146, 14,8),
   (147, 14,9),

  -- procuration
  
   (148,15,1),
   (149,15,2),
   (150,15,3),
   (151,15,4),
   (152,15,5),
   (153,15,6),

  -- CIVP
   (154, 19,1),
   (155, 19,2),
   (156, 19, 3),
   (157, 19, 4),
   (158, 19, 5),
   (159, 19, 6),
   (160, 19, 7),
   (161, 19, 8),
   (162, 19, 9),
   (163, 19, 10),
   (164, 19, 11),
   (165, 19, 12),
   (166, 19, 13),
   (167, 19, 14),
   (168, 19, 15),
   (169, 19, 16),
   (170, 19, 17),
   (171, 19, 18),
   (172, 19, 19),
   (173, 19, 20),
   (174, 19, 21),
   (175, 19, 22),
   (176, 19, 23),
   (177, 19, 24),
   (178, 19, 25),
   (179, 19, 26),
   (180, 19, 27),
   (181, 19, 28),
   (182, 19, 29),

   -- NDA
   (183, 2,1),
   (184, 2,2),
   (185, 2, 2),
   (186, 2, 3),
   (187, 2, 4),
   (188, 2, 5),
   (189, 2, 6),
   (190, 2, 7),

-- Pret_entre_parti
   (191, 4,1),
   (192, 4,2),
   (193, 4, 3),
   (194, 4, 4),
   (195, 4, 5),
   (196, 4, 6),
   (197, 4, 7),
   (198, 4, 8),
   (199, 4, 9),
   (200, 4, 10);


INSERT INTO etafakna.questions_has_contract_types_FR(questions_id, contract_types_id, order_question)
VALUES

-- Questions Demande Officielle
   (1, 14, 1),
   (2, 14, 2),
   (3, 14, 3),
   (4, 14, 4),
   (5, 14, 5),
   (6, 14, 6),
   (7, 14, 7),
   (8, 14, 8),

   -- CDD
   (9 , 18, 1),
   (10, 18, 2),
   (11, 18, 3),
   (12, 18, 4),
   (13, 18, 5),
   (14, 18, 6),
   (15, 18, 7),
   (16, 18, 8),
   (17, 18, 9),
   (18, 18, 10),
   (19, 18, 11),
   (20, 18, 12),
   (21, 18, 13),
   (22, 18, 14),
   (23, 18, 15),
   (24, 18, 16),
   (25, 18, 17),
   (26, 18, 18),
   (27, 18, 19),
   (28, 18, 20),

   -- CONTRACT DE LOCATION A USAGE Bureau
   (29, 20, 1),
   (30, 20, 2),
   (31, 20, 3),
   (32, 20, 4),
   (33, 20, 5),
   (34, 20, 6),
   (35, 20, 7),
   (36, 20, 8),
   (37, 20, 9),
   (38, 20, 10),
   (39, 20, 11),
   (40, 20, 12),
   (41, 20, 13),
   (42, 20, 14),
   (43, 20, 15),
   (44, 20, 16),
   (45, 20, 17),
   (46, 20, 18),
   (47, 20, 19),
   (48, 20, 20),
   (49, 20, 21),
   (50, 20, 22),
   (51, 20, 23),
   (52, 20, 24),
   (53, 20, 25),

   -- habitation
   (54, 21, 1),
   (55, 21, 2),
   (56, 21, 3),
   (57, 21, 4),
   (58, 21, 5),
   (59, 21, 6),
   (60, 21, 7),
   (61, 21, 8),
   (62, 21, 9),
   (63, 21, 10),
   (64, 21, 11),
   (65, 21, 12),
   (66, 21, 13),
   (67, 21, 14),
   (68, 21, 15),
   (69, 21, 16),
   (70, 21, 17),
   (71, 21, 18),
   (72, 21, 19),
   (73, 21, 20),
   (74, 21, 21),
   (75, 21, 22),
   (76, 21, 23),

  -- Engagement
   (77, 8, 1),
   (78, 8, 2),
   (79, 8, 3),
   (80, 8, 4),
   (81, 8, 5),
   (82, 8, 6),
   (83, 8, 7),
   (84, 8, 8),
   (85, 8, 9),
   (86, 8, 10),

   -- Domiciliation
   (87, 12, 1),
   (88, 12, 2),
   (89, 12, 3),
   (90, 12, 4),
   (91, 12, 5),
   (92, 12, 6),
   (93, 12, 7),
   (94, 12, 8),
   (95, 12, 9),
   (96, 12, 10),
   (97, 12, 11),

-- atte stage
   (98,  3, 1  ),
   (99,  3, 2  ),
   (100, 3, 3  ),
   (101, 3, 4  ),
   (102, 3, 5  ),
   (103, 3, 6  ),
   (104, 3, 7  ),
   (105, 3, 8  ),
   (106, 3, 9  ),
   (107, 3, 10 ),
   (108, 3, 11 ),
   (109, 3, 12 ),

-- CIVP 
   (110, 19, 1  ),
   (111, 19, 2  ),
   (112, 19, 3  ),
   (113, 19, 4  ),
   (114, 19, 5  ),
   (115, 19, 6  ),
   (116, 19, 7  ),
   (117, 19, 8  ),
   (118, 19, 9  ),
   (119, 19, 10 ),
   (120, 19, 11 ),
   (121, 19, 12 ),
   (122, 19, 13 ),
   (123, 19, 14 ),
   (124, 19, 15 ),
   (125, 19, 16 ),
   (126, 19, 17 ),
   (127, 19, 18 ),
   (128, 19, 19 ),
   (129, 19, 20 ),
   (130, 19, 21 ),
   (131, 19, 22 ),
   (132, 19, 23 ),
   (133, 19, 24 ),
   (134, 19, 25 ),
   (135, 19, 26 ),
   (136, 19, 27 ),
   (137, 19, 28 ),
   (138, 19, 29 ),
   (139, 19, 30 ),
   (140, 19, 31 ),
   (141, 19, 32 ),
   (142, 19, 33 ),
   (143, 19, 34 ),
   (144, 19, 35 ),
   (145, 19, 36 ),
   (146, 19, 37 ),

 -- procuration
   (147, 15, 1  ),
   (148, 15, 2  ),
   (149, 15, 3  ),
   (150, 15, 4  ),
   (151, 15, 5  ),
   (152, 15, 6  ),
   (153, 15, 7  ),
   (154, 15, 8  ),
   (155, 15, 9  ),
   (156, 15, 10 ),
   (157, 15, 11 ),
   (158, 15, 12 ),
   (159, 15, 13 ),
  
  -- freelance
   (160, 13, 1  ),
   (161, 13, 2  ),
   (162, 13, 3  ),
   (163, 13, 4  ),
   (164, 13, 5  ),
   (165, 13, 6  ),
   (166, 13, 7  ),
   (167, 13, 8  ),
   (168, 13, 9  ),
   (169, 13, 10 ),
   (170, 13, 11 ),
   (171, 13, 12 ),
   (172, 13, 13 ),
   (173, 13, 14 ),
   (174, 13, 15 ),
   (175, 13, 16 ),
   (176, 13, 17 ),
   (177, 13, 18 ),

-- vente et achat 
   (178, 7, 1  ),
   (179, 7, 2  ),
   (180, 7, 3  ),
   (181, 7, 4  ),
   (182, 7, 5  ),
   (183, 7, 6  ),
   (184, 7, 7  ),
   (185, 7, 8  ),
   (186, 7, 9  ),
   (187, 7, 10 ),
   (188, 7, 11 ),
   (189, 7, 12 ),
   (190, 7, 13 ),

-- prêt
   (191, 4, 1  ),
   (192, 4, 2  ),
   (193, 4, 3  ),
   (194, 4, 4  ),
   (195, 4, 5  ),
   (196, 4, 6  ),
   (197, 4, 7  ),
   (198, 4, 8  ),
   (199, 4, 9  ),
   (200, 4, 10 ),
   (201, 4, 11 ),
   (202, 4, 12 ),
   (203, 4, 13 ),

   -- vente voiture
   (204, 22, 1  ),
   (205, 22, 2  ),
   (206, 22, 3  ),
   (207, 22, 4  ),
   (208, 22, 5  ),
   (209, 22, 6  ),
   (210, 22, 7  ),
   (211, 22, 8  ),
   (212, 22, 9  ),
   (213, 22, 10 ),
   (214, 22, 11 ),
   (215, 22, 12 ),
   (216, 22, 13 ),
   (217, 22, 14 ),
   (218, 22, 15 ),
   (219, 22, 16 ),
   (220, 22, 17 ),
   (221, 22, 18 ),
   (222, 22, 19 ),

    -- NDA societe
   (223, 28, 1  ),
   (224, 28, 2  ),
   (225, 28, 3  ),
   (226, 28, 4  ),
   (227, 28, 5  ),
   (228, 28, 6  ),
   (229, 28, 7  ),
   (230, 28, 8  ),
   (231, 28, 9  ),
   (232, 28, 10 ),
   (233, 28, 11 ),
   (234, 28, 12 ),
   (235, 28, 13 ),
   (236, 28, 14 ),
   (237, 28, 15 ),
   (238, 28, 16 ),

 -- NDA particulier
   (239, 29, 1  ),
   (240, 29, 2  ),
   (241, 29, 3  ),
   (242, 29, 4  ),
   (243, 29, 5  ),
   (244, 29, 6  ),
   (245, 29, 7  ),
   (246, 29, 8  ),
   (247, 29, 9  ),
   (248, 29, 10 ),
   (249, 29, 11 ),
   (250, 29, 12 ),
   (251, 29, 13 ),
   (252, 29, 14 ),
   (253, 29, 15 ),
   (254, 29, 16 ),

  -- atte travail 
   (255, 31, 1  ),
   (256, 31, 2  ),
   (257, 31, 3  ),
   (258, 31, 4  ),
   (259, 31, 5  ),
   (260, 31, 6  ),
   (261, 31, 7  ),
   (262, 31, 8  ),
   (263, 31, 9  ),

  -- Commision
   (264, 16, 1  ),
   (265, 16, 2  ),
   (266, 16, 3  ),
   (267, 16, 4  ),
   (268, 16, 5  ),
   (269, 16, 6  ),
   (270, 16, 7  ),
   (271, 16, 8  ),
   (272, 16, 9  ),
   (273, 16, 10 ),
   (274, 16, 11 ),
   (275, 16, 12 ),

  -- att Honneur
   (276, 11, 1  ),
   (277, 11, 2  ),
   (278, 11, 3  ),
   (279, 11, 4  ),
   (280, 11, 5  ),
   (281, 11, 6  ),
   (282, 11, 7  ),

  -- CDI
   (283, 17, 1  ),
   (284, 17, 2  ),
   (285, 17, 3  ),
   (286, 17, 4  ),
   (287, 17, 5  ),
   (288, 17, 6  ),
   (289, 17, 7  ),
   (290, 17, 8  ),
   (291, 17, 9  ),
   (292, 17, 10 ),
   (293, 17, 11 ),
   (294, 17, 12 ),
   (295, 17, 13 ),
   (296, 17, 14 ),
   (297, 17, 15 ),
   (298, 17, 16 ),
   (299, 17, 17 ),
   (300, 17, 18 ),
   (301, 17, 19 ),
   (302, 17, 20 ),
   (303, 17, 21 ),
   (304, 17, 22 ),
   (305, 17, 23 ),
   (306, 17, 24 ),

  -- LOCATION DE VOITURE
   (307, 23, 1  ),
   (308, 23, 2  ),
   (309, 23, 3  ),
   (310, 23, 4  ),
   (311, 23, 5  ),
   (312, 23, 6  ),
   (313, 23, 7  ),
   (314, 23, 8  ),
   (315, 23, 9  ),
   (316, 23, 10 ),
   (317, 23, 11 ),
   (318, 23, 12 ),
   (319, 23, 13 ),
   (320, 23, 14 ),
   (321, 23, 15 ),
   (322, 23, 16 ),
   (323, 23, 17 ),
   (324, 23, 18 ),
   (325, 23, 19 ),
   (326, 23, 20 ),
   (327, 23, 21 ),
   (328, 23, 22 ),
   (329, 23, 23 ),

  -- prestation service
   (330, 32, 1  ),
   (331, 32, 2  ),
   (332, 32, 3  ),
   (333, 32, 4  ),
   (334, 32, 5  ),
   (335, 32, 6  ),
   (336, 32, 7  ),
   (337, 32, 8  ),
   (338, 32, 9  ),
   (339, 32, 10 ),
   (340, 32, 11 ),
   (341, 32, 12 ),
   (342, 32, 13 ),
   (343, 32, 14 ),
   (344, 32, 15 ),
   (345, 32, 16 ),
   (346, 32, 17 ),
   (347, 32, 18 ),
   (348, 32, 19 ),
   (349, 32, 20 ),
   (350, 32, 21 ),

  -- Patenariat
   (351, 9, 1  ),
   (352, 9, 3  ),
   (353, 9, 4  ),
   (354, 9, 5  ),
   (355, 9, 6  ),
   (356, 9, 8  ),
   (357, 9, 9  ),
   (358, 9, 10 ),
   (359, 9, 2  ),
   (360, 9, 11 ),
   (361, 9, 7  ),
   (362, 9, 12 ),
   (363, 9, 13 ),
   (364, 9, 14 ),
   (365, 9, 15 ),
   (366, 9, 16 ),
   (367, 9, 17 );


-- Insert All Contracts
INSERT INTO
  etafakna.users(
    first_name,
    last_name,
    username,
    email,
    password,
    address,
    phone,
    role,
    image,
    status,
    created_at
  )
VALUES
(
    "fares",
    "fares",
    "fares",
    "faroussassg007@gmail.com",
    "$2b$10$sIzEhADNfPcEOUCO7ILtAunEbf8Y9YVQt2/gTaZ0TvHvNA3bN6U1O",
    "boumhale",
    "122883",
    "user",
    "https://res.cloudinary.com/dew6e8h2m/image/upload/v1664624355/cld-sample.jpg",
    "Activated",
    "2022-09-29"
  ),
  (
    "omar",
    "omar",
    "omar",
    "massoudiomar54321@gmail.com",
    "$2b$10$sIzEhADNfPcEOUCO7ILtAunEbf8Y9YVQt2/gTaZ0TvHvNA3bN6U1O",
    "Beja",
    "122883",
    "user",
    "https://res.cloudinary.com/dew6e8h2m/image/upload/v1664624356/cld-sample-3.jpg",
    "Activated",
    "2022-09-29"
  ),
  (
    "Norchen",
    "Mezni",
    "Norchen Mezni",
    "Norchenmezni1@gmail.com",
    "$2b$10$kzeiOtT.FvnFlD175KxSHe1VhrFJ.OUtIcq.5C4YprY6qjDvWz3/a",
    "Tunis",
    "52979979",
    "user",
    "null",
    "Activated",
    "2022-09-29"
  );




-- Insert All Contracts
INSERT INTO
  etafakna.contract_types(
    signed_time,
    time_answering,
    title_EN,
    title_FR,
    title_AR,
    description_FR,
    description_AR,
    description_EN,
    image_url,
    template_FR,
    template_AR,
    template_EN,
    country,
    types,
    categories,
    inside_categories
  )
VALUES 
(
   0,
    5,
    "Employment",
    "Travail",
    N'عقد التوظيف',
    "Anything can be rented using E-tafakna e-greement... From a room, to an appartement or a car...",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/travaille_y5oqzh.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "types",
    "categories",
    "null"
  ),
-- (
--     0,
--     5,
--     "Commercial rental",
--     "Location commercial",
--     N'عقد كراء محل تجاري',
--     "desc_fr",
--     "desc_AR",
--     "desc_EN",
--     "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/cdd_qmrm8e.png",
--     "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317354/5._Loc_commerciale_AR_ffffff_fzvxbe_wriymj.docx",
--     "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
--     "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
--     "Tunisia",
--     "types",
--     "categories",
--     "null"
--   ),
  (
0,
    5,
    "Nda",
    "NDA",
    N'اتفاق غير معلن',
    "This is Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670325480/New%20icons%20contracts/unnamed_bipsgv.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670495574/11._NDA_FR___Soci%C3%A9t%C3%A91_mo8pav.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671187200/NDA_ARABE_1_kqwkq6.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671187226/NDA_ARABE_2_rj0zge.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "nda",
    "null"
  ),
  (
0,
    5,
    "Training Certificate",
    "Attestation",
    N'شهادة تربص',
    N'Lattestation de stage E-Tafakna, aussi appelée le certificat de stage, est un document remis au stagiaire permettant de valider une expérience professionnelle au sein de lentreprise.',
    "desc_AR",
    "In the broadest sense, a training certificate is a document certifying that the holder has taken a specific course of training.",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/stage_ignntm.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670845854/Attestation-de-stage_n2_fffffffffffffffffffff_vskvis_1_os9fqw_imxrxt_1_arsmzt.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317650/_1._Attestation_Stage_AR_fffffff_vjv8jp_2_z3llel.docx",
    "null",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (0,
    5,
    "Microcredit",
    N'Prêt entre particuliers ',
    N'قرض بين الأفراد',
    "This is loan Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/pret_entre_particulier_vygdo9.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670945118/13._Pret_entre_partic_FR_lmg0o8.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670341104/16._Pret_entre_partic_AR_je3ftv.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
0,
    5,
    "Car",
    "Voiture",
    N' سيارة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/car_fh1tdl.png",
    "temp_FR",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "car",
    "null"
  ),
  (
   0,
    5,
    "Rental of real estate",
    "Location de biens",
    N'تأجير العقارات',
    N'Tout peut être loué en utilisant le contrat de location de E-Tafakna. Dune chambre, une villa, un appartement, à un bureau. Quil s&#39;agisse d`une location à court terme ou à long terme',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/location_de_bien_prywdl.png",
    "temple_FR",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "categorie",
    "null"
  ),
  (
0,
    5,
    "Sale and purchase",
    "Vente et Achat",
    N'بيع وشراء',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/Vente_Achat_duuhpn.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670944235/10.Vente_Achat_FR_hmvixs.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671184855/12.Vente_simple_AR_2_fiaul1_1_uilsqj_jxwf1h.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1664737567/Template_Contrat_de_location_bureau_n3_xvsszr.docx",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
  0,
    5,
    N'Engagement',
    N'Engagement',
    N'التزام',
    N'Le contrat d’engagement E-Tafakna nous permet de nous assurer que vous soyez prêt à entreprendre des travaux, avant de commencer à travailler plus en profondeur sur votre projet.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/engagement_usouyg.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670927184/20._Engagement_contract_xukdvd.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670319265/7._Engagement_fff_pduwtc_rhu0nk.docx",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665770960/WORD-CONTRACTS/Engagement_contract_n2_x14mz3_wg8rm1_gukspl.docx",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
 0,
    5,
    "Partnership",
    "Partenariat",
    N'عقد شراكة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/partenariat_ze8q6p.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671176316/Document_sans_titre_37_lcare7.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671176343/Document_sans_titre_38_q3fjgo.docx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
0,
    5,
    "Quotation/Bill",
    "Devis/Facture ",
    N'فاتورة/devis',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308746/New%20icons%20contracts/Devis_facture_yg4aee.png",
    "https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "types",
    "facture",
    "null"
  ),
  -- (
  --   0,
  --   5,
  --   "Travel insurance",
  --   "Assurance Voyage",
  --   N'تامين السفر',
  --   "This is Employment Contract Description",
  --   "desc_AR",
  --   "desc_EN",
  --   "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949430/icons/assurance_voyage_rrv8ql.png",
  --   "temp_FR",
  --   "temp_AR",
  --   "temp_EN",
  --   "Tunisia",
  --   "types",
  --   "null",
  --   "null"
  -- ),
  (
0,
    5,
    "Certificate of honor",
    N'Attestation sur l`honneur',
    N'تصريح على الشرف',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/decalaration_sur_lhonneur_ajcbuh.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671012604/15._Attestion_sur_l_honneur_FR_k5kfzu.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670319436/8._Attes_sur_l_honneur_AR_fffffff_x2vw0v_1_ofywd0.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  -- (
  --   0,
  --   5,
  --   "CV",
  --   "CV",
  --   N'أمر شراء',
  --   "This is Employment Contract Description",
  --   "desc_AR",
  --   "desc_EN",
  --   "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/exlusivite_fodbew.png",
  --   "temp_FR",
  --   "temp_AR",
  --   "temp_EN",
  --   "Tunisia",
  --   "types",
  --   "null",
  --   "null"
  -- ),
  (
 0,
    5,
    "Safe of real estate",
    "Domiciliation",
    N'شهادة في ايواء شركة',
    N'Le contrat de domiciliation E-Tafakna est une obligation pour toutes les sociétés, mais également pour les associations. Il sagit de ladresse administrative et fiscale à laquelle tous les courriers seront envoyés.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308746/New%20icons%20contracts/domicilation_lucacc.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670947743/12._Domiciliation_3_bqokrh_rnvj4r.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670320688/6._Domiciliation_AR_1_ffff1_omhmkn_gxoxek.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
   (
0,
    5,
    "Freelancer",
    "Freelance",
  N'عقد عمل حر',
    "This is Freelancer Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/freelance_uydcui.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670942546/6.Freelance_FR_yxydei.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321228/10._Freelance_AR_1_em839z_2_tzkeho.docx",
    "temp_EN",
    "Tunisia",
  "types",
    "freelance",
     "null"
  ),
  (
 0,
    5,
    "Official request",
    "Demande officielle",
    N'مطلب رسمي',
    N'Une demande Officielle E-Tafakna constitue effectivement une preuve réelle de la démarche engagée que l`on peut réaliser et apporter à toutes fins utiles.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308746/New%20icons%20contracts/demande_offficiel_kyzndt.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670849725/Demande_officielle_n4_m4cbe4_cfrc9c_1_u7vxsu_qpk8df.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671185389/9._Demande_AR_2_xvle6d_ftdfak_xsxamn.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
    
  ),
  (
0,
    5,
    "Power of attorney",
    "Procuration",
    N'توكيل',
    N'Desc_FR',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/procuration_nin84y.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670938116/9._Procuration_FR_1_b9prrb.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671185698/14._Procuration_AR_qhjo5o_1_glwp36_fayo9a.docx",
    "temp_EN",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
   0,
    5,
    "reference",
    "Commision",
    N'wasata',
    "Anything can be rented using E-tafakna e-greement... From a room, to an appartement or a car...",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/travaille_y5oqzh.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671010791/11._Commission_FR_bw5cgq.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "types",
    "null",
    "null"
  ),
  (
    0,
    5,
    "CDI",
    "CDI",
    N'عقد عمل غير محدد المدة',
    "CDI",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457759/unnamed_2_1_ztst4g.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671025014/Document_sans_titre_25_os3zlg.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671025039/Document_sans_titre_26_yjfpjj.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671181865/CDI_ARABE_I_xtgow2.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671181891/CDI_ARABE_2_rvqyfk.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "work",
    "categories",
    "inside_categories"
  ),
  (
    0,
    5,
    "CDD",
    "CDD",
    N'عقد عمل محدد المدة',
    N'Le contrat à durée déterminée (CDD) E-Tafakna est un contrat de travail par lequel un employeur recrute un salarié pour une durée limitée. Un tel contrat n’est possible que pour l’exécution d’une tâche précise et temporaire et seulement dans les cas énumérés par la loi.',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457759/unnamed_2_1_ztst4g.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670853604/CDD_PART1_ziswne.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670852791/3._CDD_FR_ugesnp.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671181388/CDD_ARABE_rbo7gs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671181199/CDD_ARABE_2_knnnay.docx",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665748919/WORD-CONTRACTS/contract1_isna08_1_part1_esqffs_ycbrtu.docx,https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/raw/upload/v1665748967/WORD-CONTRACTS/contract2_fiwvof_part2_i550oc_doi7zp.docx",
    "Tunisia",
    "work",
    "categories",
    "inside_categories"
  ),
  (
    0,
    5,
    "CIVP",
    "CIVP",
    N'عقد الإعداد للحياة المهنية',
    "CIVP",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457759/unnamed_2_1_ztst4g.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670936326/Document_sans_titre_10_edbrox.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670936347/Document_sans_titre_11_mtka89.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670936368/Document_sans_titre_12_qunmbq.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670936389/Document_sans_titre_13_ljal1s.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671186184/CIVP_ARABE_1_bqvoug.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671186213/CIVP_ARABE_2_ovxeh4.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671186233/CIVP_ARABE_3_zcaoja.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084720/contract1_isna08_1_part1_esqffs.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1665084831/contract2_fiwvof_part2_i550oc.docx",
    "Tunisia",
    "work",
    "categories",
    "inside_categories"
  ),
  (
    0,
    5,
    "Rental of real estate",
    N'Location à usage de bureau',
    N'تأجير للاستخدام المكتبي',
    N'Tout peut être loué en utilisant le contrat de location de E-Tafakna. D`une chambre, une villa, un appartement, à un bureau. Qu`il s’agisse d`une location à court terme ou à long terme',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457757/unnamed_16_1_drpr0x.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670926236/Document_sans_titre_1_zqfoit_2_p7j2xo.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670922587/Document_sans_titre_3_spsujy.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671182890/COMMERCIAL_ARABE_1_dqb9yq.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671182506/COMMERCIAL_ARABE_2_ii9us6.docx",
    "temp_EN",
    "Tunisia",
    "work",
    "null",
    "inside_categorie"
  ),
  (
    0,
    5,
    "Rental of real estate",
    N'Location à usage d’habitation',
    N'عقد كراء محل سكني',
    N'Tout peut être loué en utilisant le contrat de location de E-Tafakna. D`une chambre, une villa, un appartement, à un bureau. Qu`il s’agisse d`une location à court terme ou à long terme',
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dfctzd9p3/image/upload/v1664457757/unnamed_16_1_drpr0x.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671021775/Document_sans_titre_4_a0y93b_fjw3bi.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671021851/Document_sans_titre_5_kyhgi0_1_ncopru.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671182162/HABITATION_ARABE_I_qhfj2h.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671182188/HABITATION_ARABE_2_wivodw.docx",
    "temp_EN",
    "Tunisia",
    "work",
    "null",
    "inside_categorie"
  ),
    (
    0,
    5,
    "Car sale",
    "Vente de voiture",
    N'عقد بيع سيارة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949430/icons/achat_voiture_j3ikzr.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670945637/14._Vente_voiture_FR_d7onih.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317991/11.Vente_voiture_AR_mwvqsr_ksuchi.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670244199/9._Vente_voiture_FR_nubcjp.docx",
    "Tunisia",
    "null",
    "categories",
    "car_categorie"
  ),
    (
    0,
    5,
    "Car sale",
    "Location de voiture",
    N'عقد كراء سيارة',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949430/icons/achat_voiture_j3ikzr.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671028430/15._Location_de_VOITURE_1_nxju1r.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317991/11.Vente_voiture_AR_mwvqsr_ksuchi.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670244199/9._Vente_voiture_FR_nubcjp.docx",
    "Tunisia",
    "null",
    "categories",
    "car_categorie"
  ),
    (
    0,
    5,
    "Quotation/Bill",
    "Devis ",
    N'فاتورة/التسعير',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/facture_devis_ox5oml.png",
    "https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "null",
    "categories",
    "facture"
  ),
    (
    0,
    5,
    "Quotation/Bill",
    "Devis ",
    N'فاتورة/التسعير',
    "This is Employment Contract Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949431/icons/facture_devis_ox5oml.png",
    "https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx",
    "temp_AR",
    "temp_EN",
    "Tunisia",
    "null",
    "categories",
    "facture"
  ),
    (
    0,
    5,
    "Normal person",
    "Personne normale",
  N'Personne normale',
    "This is Freelancer Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949432/icons/freelance_zbfpcj.png",
    "temp_FR",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671183665/10._Freelance_AR_1_em839z_2_tzkeho_2_n6fnfo.docx",
    "temp_EN",
    "Tunisia",
   "freelance",
    "categories",
    "freelancee"
  ),
   (
    0,
    5,
    "Company",
    N'Société',
  N'Société',
    "This is Freelancer Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1665949432/icons/freelance_zbfpcj.png",
    "temp_FR",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670321357/10._Freelance_AR_4_dkpgy7_cedcvw.docx",
    "temp_EN",
    "Tunisia",
    "freelance",
    "categories",
    "freelancee"
  ),
    (
0,
    5,
    "Nda",
    N'Protger votre société',
    N'اتفاق غير معلن',
    "This is Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670325480/New%20icons%20contracts/unnamed_bipsgv.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670948028/Document_sans_titre_17_fpluor.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670948059/Document_sans_titre_18_xpcx25.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670948080/Document_sans_titre_19_zxipgb.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670323620/15._NDA_AR_xlzy9t.docx",
    "temp_EN",
    "Tunisia",
    "null",
    "categories",
    "inside_nda"
  ),
  (
0,
    5,
    "Nda",
    N'Protger votre projet',
    N'اتفاق غير معلن',
    "This is Description",
    "desc_AR",
    "desc_EN",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670325480/New%20icons%20contracts/unnamed_bipsgv.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671008024/Document_sans_titre_20_xewehq.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671008057/Document_sans_titre_21_ztw43g.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671008072/Document_sans_titre_22_pem8xr.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670323620/15._NDA_AR_xlzy9t.docx",
    "temp_EN",
    "Tunisia",
    "null",
    "categories",
    "inside_nda"
  ),
    (
0,
    5,
    "Training Certificate",
    "Attestation de stage",
    N'شهادة تربص',
    N'Lattestation de stage E-Tafakna, aussi appelée le certificat de stage, est un document remis au stagiaire permettant de valider une expérience professionnelle au sein de lentreprise.',
    "desc_AR",
    "In the broadest sense, a training certificate is a document certifying that the holder has taken a specific course of training.",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/stage_ignntm.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670933770/1._Attestation_de_stage_FR_pw2dxk.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317650/_1._Attestation_Stage_AR_fffffff_vjv8jp_2_z3llel.docx",
    "null",
    "Tunisia",
    "null",
    "null",
    "attestation"
  ),
    (
0,
    5,
    "Training Certificate",
    "Attestation de travail",
    N'شهادة تربص',
    N'Lattestation de travail de E-Tafakna est une attestation délivrée par lemployeur à un salarié, sur sa demande, permettant détablir officiellement, vis-à-vis des tiers, que le salarié est bien employé par lentreprise.',
    "desc_AR",
    "In the broadest sense, a training certificate is a document certifying that the holder has taken a specific course of training.",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/stage_ignntm.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671021376/5._Attestation_de_travail_FR_1_gmtczq.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317650/_1._Attestation_Stage_AR_fffffff_vjv8jp_2_z3llel.docx",
    "null",
    "Tunisia",
    "null",
    "null",
    "attestation"
  ),
      (
0,
    5,
    "Training Certificate",
    "Prestation de servie",
    N'شهادة تربص',
    N'Lattestation de travail de E-Tafakna est une attestation délivrée par lemployeur à un salarié, sur sa demande, permettant détablir officiellement, vis-à-vis des tiers, que le salarié est bien employé par lentreprise.',
    "desc_AR",
    "In the broadest sense, a training certificate is a document certifying that the holder has taken a specific course of training.",
    "https://res.cloudinary.com/dcscfcsdfrefrefreferfersdfersdf/image/upload/v1670308745/New%20icons%20contracts/stage_ignntm.png",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671119996/Document_sans_titre_35_uurvif.docx,https://res.cloudinary.com/dew6e8h2m/raw/upload/v1671120126/Document_sans_titre_36_qszadl.docx",
    "https://res.cloudinary.com/dew6e8h2m/raw/upload/v1670317650/_1._Attestation_Stage_AR_fffffff_vjv8jp_2_z3llel.docx",
    "null",
    "Tunisia",
    "types",
    "null",
    "null"
  );

-- INSERT INTO
--   etafakna.contract_types(
--     signed_time,
--     time_answering,
--     title_EN,
--     title_FR,
--     title_AR,
--     description_FR,
--     description_AR,
--     description_EN,
--     image_url,
--     template_FR,
--     template_AR,
--     template_EN,
--     country,
--     types,
--     categories,
--     inside_categories
--   )
-- VALUES
-- (
-- 0, 
-- 5, 
-- 'Facture', '
-- Facture', 
-- 'Facture', 'Facture', 
-- 'Facture', 
-- 'Facture', 
-- 'https://res.cloudinary.com/dn6kxvylo/image/upload/v1665584941/quotation_cx1xtp.png',
-- 'https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx',
-- 'https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx',
-- 'https://res.cloudinary.com/dn6kxvylo/raw/upload/v1665755893/Template_facture_ymmtjd.xlsx',
-- 'tunisie', 
-- 'types',
-- NULL, 
-- NULL);
